### ISSUE TITLE
debug log 출력 방식 일치

### ISSUE THREAD

**Issue by whchoi83** [naver/arcus-java-client#102]
본 이슈는 jam2in arcus-java-client [debug log 출력 방식 일치](https://github.com/jam2in/arcus-java-client/issues/15) 에서 옮겨왔습니다.

java client 전체적으로 debug log 를 출력할 때 아래와 같이 두 가지 방식을 혼용하고 있다.
한 가지 방식으로 통일한다.

``` java
        getLogger().debug("Got line %s", line);
```

``` java
        if (getLogger().isDebugEnabled()) {
            getLogger().debug("Got line %s", line);
        }
```

**Comment by whchoi83** [comment]
isDebugEnabled flag 를 항상 확인하도록 통일합니다.

**Comment by whchoi83** [comment]
logger 의 debug 메소드는 아래 3가지 종류가 존재하는데, 
```java
public void debug(Object message, Throwable exception)
public void debug(String message, Object... args)
public void debug(Object message)
```
toString 호출이 필요한 ```debug(String message, Object... args)``` 는 내부에서 isDebugEnabled 를 호출하도록 처리되어있다. 즉, 아래와 같이 호출하는 것이 올바른 형태이다.
```java
getLogger().debug("Got line %s", line);
```

단, 나머지 두 가지 형태의 debug 메소드에 대해서는 아래와 같이 사용하는 경우, 
```java
getLogger().debug("Got line " + line);
```
아래 두 가지 중에 하나로 선택해서 사용해야 한다.
(가급적이면 두 번째를 사용할 것을 권장)
1. isDebugEnabled 를 사용
```java
if (getLogger().isDebugEnabled()) {
    getLogger().debug("Got line " + line);
}
```

2. String format 형태의 debug 메소드 사용
```java
getLogger().debug("Got line %s", line);
```

**Comment by whchoi83** [comment]
불필요하게 isDebugEnabled 를 확인하는 곳이나, 호출해야 하는데 호출하지 않는 곳에 대해서 정리합니다.

**Comment by jhpark816** [comment]
debug 메세지 기록에서 간단한 형태는 아래와 같이 변경하는 것이 어떤가요 ?

```
getLogger().debug("Got line " + line);
=>
getLogger().debug("Got line %s", line);
```

**Comment by whchoi83** [comment]
참고로 log4j 의 경우는 API 내부에서 해당 log level 의 isEnabled 를 확인하도록 되어있다.

**Comment by whchoi83** [comment]
@jhpark816 
위에도 작성했지만,
간단한 형태 역시 string formatter 를 사용하는 형태로 작성하도록 하는 것이 안전한 형태이고,
+ 연산을 이용해 concatenation 하는 log 가 있다면 string formatter 를 사용하도록 수정할 계획입니다.

**Comment by jhpark816** [comment]
@hjyun328 
이 작업 진행할 필요가 있는 지를 확인 바랍니다.

**Comment by hjyun328** [comment]
@jhpark816 
코드 퀄리티를 고려해야 한다면 진행할 필요는 있겠으나, 버그 성격의 이슈가 아니므로 급하게 수정이 필요한 작업은 아닌 것으로 생각합니다.

어쨌든 작업을 진행한다면 금방 수정이 가능할 것으로 보입니다.

**Comment by hjyun328** [comment]
debug 메소드 내부에서 isDebugEnabled 조건문으로 분기되어있고, args들을 포맷팅해주기 때문에
isDebugEnabled 조건문과, debug가 enabled되지 않을 시, 문자열 연결에 따른 garbage를 줄이기 위해 

```java
if (getLogger().isDebugEnabled()) {
    getLogger().debug("Got line " + line);
}
``` 형태의 코드를

```java
getLogger().debug("Got line %s", line);
```

로 변경하는 것이 맞는 것 같습니다.

@SEONGMINY 
이슈 확인해주시고 수정 부탁드립니다.

**Comment by hjyun328** [comment]
https://github.com/naver/arcus-java-client/pull/423 PR 반영되어 클로즈합니다.
