### ISSUE TITLE
Migration 기능 추가

### ISSUE THREAD

**Issue by whchoi83** [naver/arcus-java-client#104]
본 이슈는 jam2in repository의 "[Migration 기능 추가](https://github.com/jam2in/arcus-java-client/issues/20)" 에서 옮겨왔습니다.

Client 동작에 필요한 migartion 정책 논의가 완료된 후에 개발을 시작합니다.
자세한 진행 과정은 [arcus-memcached EE ver. 의 issue](https://github.com/jam2in/arcus-memcached-EE/issues) 에서 migration 과 관련된 내용을 참고하시면 됩니다.

**Comment by uhm0311** [comment]
https://github.com/naver/arcus-java-client/pull/536

위 PR로 반영되어 close 합니다.
