### ISSUE TITLE
윈도우 환경에서 Arcus java client 객체 생성 시  ZK admin 연결이 실패하는 현상

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#11]

**Comment by jhpark816** [comment]
ZooKeeper 연결 시,
InetSocketAddress의 getHostName()을 호출하는 부분에서 reverse DNS lookup을 수행하게 되며,
이러한 reverse DNS lookup은 아래의 다양한 시도를 하게 되며, 이 과정에서 5초 delay가 발생한다.

- DNS lookup 
- host file lookip 
- WINS or NetBIOS lookup

위의 DNS lookup과 host file lookup은 그 수행이 빨리 끝나지만,
NetBIOS lookup에서 5초 delay가 발생한다.

**Comment by jhpark816** [comment]
arcus-java-client에서 ZK Admin에의 connect timeout을 현재 2초 => 5초로 늘렸으나,
ZK admin에의 연결 실패가 발생하는 경우가 종종 있다.
이러한 실패를 원천적으로 막기 위해, ZK admin에의 connect timeout을 
ZK session timeout으로 늘릴 필요가 있다.

참고로, ZooKeeper 내부에서도 실제 ZK session timeout 만큼 connect를 시도하기 때문에,
arcus-java-client에서 ZK admin에의 connect timeout을 ZK session timeout으로 설정하는
것이 타당하다고 본다.

**Comment by hyongyoubkim** [comment]
예, 타임아웃 길이 조정이 필요해 보입니다.  Name lookup 하는 부분을 응용에서 바로 제어하는 방업은 없어 보입니다.

**Comment by hoonmin** [comment]
NetBIOS lookup에 대해서는 전혀 인지를 못하고 있었는데 잘 발견해주신 것 같습니다!
connect timeout 길이 조정에 대해서는 이견 없습니다.

**Comment by jhpark816** [comment]
commit link - https://github.com/naver/arcus-java-client/commit/a9b1dc089729fdfa0c6f3ff90da1f6b609050b86
