### ISSUE TITLE
Bop decr 수행의 오류

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#111]
ArcusClientPool.java 코드를 보면, 아래와 같습니다.
확인하시고, Bop decr 관련 전체 코드를 확인하고, 수정이 필요합니다.

```
	@Override
	public CollectionFuture<Long> asyncBopDecr(String key, long subkey, int by) {
		return this.getClient().asyncBopIncr(key, subkey, by);
	}

	@Override
	public CollectionFuture<Long> asyncBopDecr(String key, byte[] subkey, int by) {
		return this.getClient().asyncBopIncr(key, subkey, by);
	}

	@Override
	public CollectionFuture<Long> asyncBopDecr(String key, long subkey,
			int by, long initial, byte[] eFlag) {
		return this.getClient().asyncBopIncr(key, subkey, by, initial, eFlag);
	}

	@Override
	public CollectionFuture<Long> asyncBopDecr(String key, byte[] subkey,
			int by, long initial, byte[] eFlag) {
		return this.getClient().asyncBopIncr(key, subkey, by, initial, eFlag);
	}
```

**Comment by jhpark816** [comment]
unit test 보강 필요.

**Comment by minkikim89** [comment]
@jhpark816 

이 이슈의 경우 ArcusClient가 아닌 ArcusClientPool을 사용해 일어난 문제인데요.

이를 테스트코드에서 잡으려면 ArcusClientPool을 이용해서 client가 가진 모든 API를
테스트하는 코드가 있어야 하는데 그런 unit test 추가해서 테스트를 보강하면 좋겠다는 말씀이신가요?

**Comment by jhpark816** [comment]
@minkikim89 

현재 unit test는 single ArcusClient 객체를 통한 테스트만 있는 거죠 ?

ArcusClientPool은 단지 Pool에 있는 ArcusClient 객체를 임의로 선택하여
그 ArcusClient로 해당 작업을 수행하는 것이 전부이기 때문에
ArcusClientPool을 직접 사용한 unit test를 별도로 둘 필요가 없다는 의미인가요 ?

**Comment by minkikim89** [comment]
@jhpark816 
네 맞습니다.

실질적으로 ArcusClientPool에서 하는 동작이
ArcusClient의 API를 콜하는 게 전부이기 때문에 따로 테스트를 하는 게 의미가 있나 싶고,

이번과 같은 케이스가 있을 수도 있다는 가정하에 테스트 코드를 짜는게 좋을 것 같다면
테스트 코드 한 파일에 ArcusClientPool API를 모두 돌려보는 코드를 짜야할 것 같습니다.

결론적으로, 제 생각을 정리하면 ArcusClientPool에서 이번처럼 버그가 발견되는 일이
흔하지 않을 것으로 보이고 눈으로 쉽게 찾을 수 있는 수준이므로,
이번에 이 버그를 수정하면서 한번 훑어보는 정도로 끝내도 되지 않나 싶습니다.

**Comment by jhpark816** [comment]
OK. unit test 추가하지  않아도되겠네요.

**Comment by jhpark816** [comment]
commit link - https://github.com/naver/arcus-java-client/commit/56f328bad80a4e94609d63e09762fd0c5a120815
