### ISSUE TITLE
log4j 보안 이슈 해결.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#190]
log4j 보안 이슈 해결을 위하여, log4j 버전을 올려야 합니다.
참고 - arcus-spring commit : https://github.com/naver/arcus-spring/commit/27db90dcc7c3e1d95bd6309303c698cdbec5af2b

**Comment by jhpark816** [comment]
@hjyun328 진행 부탁해요.

**Comment by hjyun328** [comment]
@jhpark816 

jam2in 프로젝트의  log4j 및 기타 관련 보안 경고는 전부 제거하였습니다.
https://github.com/jam2in/arcus-spring-simple-application
https://github.com/jam2in/arcus-webb

**Comment by hjyun328** [comment]
@jhpark816 
java-client는 이미 반영됐기 때문에 이슈를 닫아도 될 것 같습니다. 다른 이슈가 있다면 재오픈 부탁드립니다.
https://github.com/naver/arcus-java-client/commit/3af0d47c6279caf1a47dae1f4aae320fb6c20af5
