### ISSUE TITLE
Operation 이동에 대한 addAllOpToInputQ 동작 개선

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#202]
Replication switchover 또는 failure가 발생 후
master에서 slave의 inputQ(TCPMemcachedNodeImpl)로 operation을 이동할 때,
slave의 inputQ의 capacity를 체크하고, full 상태이면 operation을 cancel하도록 처리하고 있다.

```
public void addAllOpToInputQ(BlockingQueue<Operation> allOp) {
  for (Operation op : allOp) {
    if (inputQueue.remainingCapacity() == 0) {
      op.cancel("by moving operations");
    } else {
        op.setHandlingNode(this);
        if ((op.getState() == OperationState.WRITE_QUEUED ||
             op.getState() == OperationState.WRITING) && op.getBuffer() != null) {
          op.getBuffer().reset(); // buffer offset reset
        } else {
          op.initialize(); // write completed or not yet initialized
          op.resetState(); // reset operation state
        }
        op.setMoved(true);
      }
      addOpCount++;
      inputQueue.offer(op);
    }
}
```

slave의 inputQ가 가득찬 상태에서도 이러한 operation들을 cancel 처리하지 않도록 하는 방법이 필요하다.

**Comment by jhpark816** [comment]
@hjyun328 
보충 설명합니다.
- 무조건 cancel 처리하지 않는 것이 아니라
  timeout 없이 처리될 수 있는 연산들은 cancel 처리하지 말자는 것입니다.
   - timeout 확실시 되는 연산은 미리 cancel 처리하는 것이 낫다.
     그렇지 않은 연산은 처리 로직에 맡겨 기다려 보자는 것입니다.
   - cancel 되면, 응용에서 retry 등의 로직이 불가할 수 있기 때문에
      가급적 cancel 처리를 최소화하는 것이 나을 것 같습니다.
- 이를 정확히 구분하는 것은 불가능하고, 어림잡아 구분하는 것은 가능합니다.
  하나의 connection으로 처리가능한  최대 처리량 정도까지는 기다려보자 입니다.
   이를 확인하는 것이 일인 것 같습니다.
- 최대 처리량까지 cancel 처리하지 않는 쉬운 구현 방법은 inputQ 크기 조절입니다.
  즉, 최대 처리량 정도까지는 해당 연산을 넣을 수 있도록 inputQ 크기를 늘리면 됩니다.

**Comment by jhpark816** [comment]
@hjyun328 
처음 코멘트의 코드 link에서 L814-L832는 현재 없는 것 같습니다.
다시 올려 주세요.

**Comment by hjyun328** [comment]
@jhpark816 
변경 하였습니다. (코멘트 제거합니다.)

**Comment by jhpark816** [comment]
@hjyun328 
본 이슈에 대해 현재 상태를 정리해 주세요.

**Comment by hjyun328** [comment]
@jhpark816 
https://github.com/naver/arcus-java-client/issues/253 이슈로, 
Operation 요청 순서를 지키기 위해 아래처럼 inputQ가 아닌 writeQ에 operation 들을 옮길 수 있도록 수정되었네요.
현 이슈는 클로즈해도 될 것 같습니다. 

```java
public int addAllOpToWriteQ(BlockingQueue<Operation> allOp) {
    int movedOpCount = 0;
    for (Operation op : allOp) {
      op.setHandlingNode(this);
      if ((op.getState() == OperationState.WRITE_QUEUED ||
           op.getState() == OperationState.WRITING) && op.getBuffer() != null) {
        ((Buffer) op.getBuffer()).reset(); // buffer offset reset
      } else {
        op.initialize(); // write completed or not yet initialized
        op.resetState(); // reset operation state
      }
      if (writeQ.offer(op)) {
        op.setMoved(true);
        movedOpCount++;
      } else {
        op.cancel("by moving operations");
      }
    }
    addOpCount += movedOpCount;
    return movedOpCount;
  }
```
