### ISSUE TITLE
VersionOperation 처리 검토

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#208]
VersionOperation이 취소되거나 실패가 발생한 후, 도중 BTree GetBulk와 같은 Operation이 추가될 때, 이 Operation이 Version Operation보다 inputQ 앞단에 위치하게되어, 서버가 잘못된 프로토콜의 Operation을 수신받을 수 있음.

1. Application 시작
2. VersionOperation을 inputQ에 추가
3. Application에서 BTreeGetBulkOperation을 inputQ에 추가
4. VersionOperation write 
5. VersionOperation 타임아웃 발생
6. BTreeGetBulkOperation write
7. 다음 handleIO에서 VersionOperation을 inputQ에 추가
8. 서버는 BTreeGetBulkOperation을 먼저 수신함. 하지만 Version을 고려하지 않은 잘못된 Operation을 수신받았으므로 캐시 서버는 다운됨

Version에 따라 프로토콜이 달라지는 Operation의 경우, 즉.. https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java#L601-L628 코드의 플래그를 사용하는 Operation의 경우 클라이언트에서 Version이 완벽하게 수신하지 않았으면, 이 Operation에 대해서 inputQ에 추가하지 못하도록 cancel 처리해야 할 것 같습니다.

이 이슈에 대해 검토 바랍니다.

**Comment by MinWooJin** [comment]
@hjyun328 
서버는 Mget과 spacesaperated 에 대해서 backward compatibility를 보장하고 있는데
테스트 결과 에러가 난건가요?

**Comment by hjyun328** [comment]
@MinWooJin 

TCPMemcachedNodeImpl에서 enabledSpaceSeparate 플래그가 false로 세팅하고 

BaseLongKeyTest의 testBtree_MGet_Long, testBtree_SMGet_Long 테스트를 진행하면 캐시서버가 다운됩니다. 

참고로 server 버전은 1.11.6 입니다.

**Comment by MinWooJin** [comment]
서버문제같은데 서버 에러를 알려주시면 확인 해보겠습니다.

**Comment by MinWooJin** [comment]
해당 이슈는 version operation과 관련 없는 문제이고,
현재 arcus-memcached develop branch에 commit 된 상태입니다.
https://github.com/naver/arcus-memcached/commit/63e11a8744cbae2e30a093401e8adfadf869df83

@hjyun328 
arcus-memcached는 backward compatibility를 지원하기 때문에 version operation이
cancel 됨으로 인해 발생하는 문제는 없습니다. #206 에서도 이러한 부분을 반영해주면 될 것 같습니다.
현재 isssue는 재현 테스트 진행 해보고 close 하면 될 것 같습니다.

**Comment by hjyun328** [comment]
해당 이슈에 대해서 internal issue로 추가된 상태여서 중복되어 클로즈 하겠습니다.
