### ISSUE TITLE
[개선] bulk service 메인 로직 최적화

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#209]
기존 bulk service 메인 로직은 2가지 이슈가 있습니다.
- Readability 떨어짐.
- 성능을 최적화 가능한 부분 존재
   - 기존 방식은 "N개 연산 단위로 연산 처리를 반복"하는 방법으로, 
     N개 연산의 처리가 완료될 때까지 next 연산을 보내지 않는다.
   - "항상 N개 연산이 동시 처리"되도록 변경하면 나은 성능을 도출할 수 있다.

이를 위해, 변경한 로직은 다음과 같다.

```
    public Map<String, CollectionOperationStatus> call() throws Exception {
      int numActiveOperations = 0;
      int posResponseReceived = 0;

      for (int pos = fromIndex; isRunnable() && pos <= toIndex; pos++) {
        try {
          if (isRunnable()) {
            future.add(pos, processItem(pos));
          }
        } catch (IllegalStateException e) {
          if (Thread.currentThread().isInterrupted()) {
            break;
          } else {
            throw e;
          }
        }
        numActiveOperations++;

        if (numActiveOperations >= DEFAULT_LOOP_LIMIT) {
          awaitProcessResult(posResponseReceived);
          posResponseReceived++;
          numActiveOperations--;
        }
      }

      while (numActiveOperations > 0) {
        awaitProcessResult(posResponseReceived);
        posResponseReceived++;
        numActiveOperations--;
      }
      return errorList;
    }
```

@minkikim89 
검토하고, 문제가 없다면 반영해 주세요.

**Comment by minkikim89** [comment]
@jhpark816 
전송해야하는 키의 개수가 DEFAULT_LOOP_LIMIT보다 클 경우의
로직의 의도가 한번에 와닿지 않습니다.
```
        if (numActiveOperations >= DEFAULT_LOOP_LIMIT) {
          awaitProcessResult(posResponseReceived);
          posResponseReceived++;
          numActiveOperations--;
        }
```
numActiveOperatons가 DEFAULT_LOOP_LIMIT 보다 클 경우
매 연산을 보낼 때마다 기존에 보내둔 연산들에 대해 하나씩 waiting하는 것으로 보이는데
한번에 모든 연산들을 처리하기보다는, 처리해야하는 개수가 DEFAULT_LOOP_LIMIT보다 클 경우는 
연산을 조금씩 처리해가도록 처리한 것인가요?
만약 이게 의도한 코드라면 DEFAULT_LOOP_LIMIT라는 변수명을 변경하는 것에 대해
조금 고민해봐야할 것 같습니다.

추가적으로 fromIndex 변수는 따로 관리될 필요가 없어보여서 그냥 0을 사용하도록 변경하는게 좋을 것 같네요.

**Comment by jhpark816** [comment]
@minkikim89 
의도는 맞습니다.

정확한 이해를 위해 예를 들어 기존 방법을 설명합니다.
- 가정) 950개 key에 대한 setBulk 작업 (DEFAULT_LOOP_LIMIT=100)
- 기존 방법의 동작
   - 처음 100개 key에 대해 set 수행하고, 응답이 모두 오기까지 대기
   - 다음 100개 key에 대해 set 수행하고, 응답이 모두 오기까지 대기
   - 위 과정을 반복
   - 마지막 50개 key에 대해 set 수행하고, 응답이 모두 오기까지 대기
-  기존 방법의 문제점
   - 100개 key에 대해 set하고 모든 응답이 올 때까지 대기하고 있음.
   - 대기하는 동안 다른 key에 대한 요청이 없음.
   - 대기하는 동안에도 최대 100개를 넘지 않는 범위에서 계속 set 요청하면 됨.

지적한 대로 naming 변경하면 좋을 것 같습니다.
- DEFAULT_LOOP_LIMIT  => ??
- fromIndex, toIndex 모두 없어도 될 것 같고,
- totalCount 대신에 keyCount 를 사용하면 될 것 같습니다.

**Comment by minkikim89** [comment]
@jhpark816 
- 변수명 짓기가 까다로운데, DEFAULT_BULKSERVICE_LOOP_LIMIT => DEFAULT_BULKSERVICE_OP_SIZE_THRESHOLD 로 생각하고 있습니다. 다른 의견 있으시면 말씀해주세요.
- 현재 bulkServiceLoopLimit를 설정하는 함수가 connectionFactory를 통해 setBulkServiceLoopLimit라는 이름으로 외부 노출되어있는 상태인데요, 이에 대해서도 네이밍 변경을 할지 고민해야합니다.
- 또, 현재 default 값이 1로 되어있는데 너무 작게 설정되어있는 것 같아 수정이 필요합니다.
- 개인적으로는 그냥 내부적으로 상수값으로 설정하는 간단하지 않을까 생각이 듭니다.

**Comment by jhpark816** [comment]
@minkikim89 
- 그러면, DEFAULT_BULKSERVICE_LOOP_LIMIT 이름을 그대로 사용하시죠.
   naming과 API 제공 방법은 기능적인 부분을 모두 정리하고 나서 다시 한번 검토하시죠.
- default 값도 나중에 수정하시죠.
  이에 대해서는 성능 관련하여 논의가 필요한 것 같습니다.

**Comment by jhpark816** [comment]
아래와 같이 반영되어 close 합니다.
- commit link: https://github.com/naver/arcus-java-client/commit/5b710b9f9b1f5d6b7bd0fc0fad96f7a5df7ccbe6

@minkikim89 
작업 완료되면, 이슈는 close 처리해 주세요.

**Comment by minkikim89** [comment]
@jhpark816 
DEFAULT_BULKSERVICE_LOOP_LIMIT 명칭에 대한 논의와 API 변경,
default 값에 대한 논의도 이 이슈에서 다룰 것으로 생각하고 있었습니다.
별개의 이슈를 생성해둘까요?

**Comment by jhpark816** [comment]
@minkikim89 
그렇군요.
별도 이슈로 다루시죠.
