### ISSUE TITLE
bulkServiceLoopLimit API명에 대한 변경 검토

### ISSUE THREAD

**Issue by minkikim89** [naver/arcus-java-client#212]
현재 bulkService는 코드가 변경 되어 더 이상 loop 형태로 데이터를 전송하지 않는다.
bulkServiceLoopLimit 변수 값은 이전과 다르게 한번에 보내는 연산의 양이 너무 많이 쌓이지 않도록 조절하는 역할만을 한다.
이에, 해당 변수명을 수정하는 것을 검토하고, 변수명이 변할 경우 API명 변경도 고려해야한다.

**Comment by minkikim89** [comment]
@jhpark816 
bulkService 사용 형태가 바뀜에 따라 bulkServiceLoopLimit API는 더 이상 사용되지 않는데요. deprecate 시키면 어떨까요?

**Comment by jhpark816** [comment]
@minkikim89 
asyncSetBulk()와 asyncDeleteBulk()에서  key 개수 제약은 두지 않았는 데, 괜찮을 까요 ? 

OK. bulk service 관련된 모든 API를 deprecated 시키면 될 것 같습니다.

**Comment by minkikim89** [comment]
deleteBulk의 경우 캐시 서버에 전달하는 프로토콜이 대부분 키스트링이기 때문에 제약이 크게 필요해보이지 않는데 asyncSetBulk의 경우는 제약이 필요할 것 같아보이네요..

**Comment by jhpark816** [comment]
사용 측면에서 키 개수를 적절히 조절할 것으로 예상은 되지만,
한꺼번에 너무 많은 연산을 수행하게 하면 다른 연산의 응답 속도에 영향을 미칩니다.
이는 SetBulk이든 DeleteBulk이든 동일합니다.
따라서, 키 개수 제약을 통해 bulkServiceLoopCount 같은 동작이 필요합니다.

많은 수의 키들이면, 그에 비례하여 천천히 수행하면 된다고 봅니다.
키 개수 제약을 100개 정도로 작게 하면 문제가 되나요 ?

예를 들어, 1000개의 키를 삭제하고자 한다면, 
결국 응용에선 100개 키 단위로 잘라서 수행하면 됩니다.
이렇게 수행하여야 다른 연산의 응답 속도에 미치는 영향을 최소화할 수 있고,
자신의 연산도 적절 크기의 bulk 연산으로 처리하기 때문에
만족스러운 응답 속도를 얻을 수 있습니다.

**Comment by minkikim89** [comment]
@jhpark816 
100 정도로 설정하는 게 적절해보이기는 하는데요,
최근에 bop 연산에서도 키개수 제약을 제외해서 collection을 포함한 연산에 키 개수 제한이 없는 상태라
SetBulk, DeleteBulk에만 이러한 제약이 추가될 시 응용에서 혼동스러워할 여지도 있고,
만약 이미 SetBulk를 사용하는 응용이 있다면 이 제약으로 인해 클라이언트 버전 업데이트 시 문제가 발생할 것 같기도 하네요.

**Comment by jhpark816** [comment]
@minkikim89 
그러면, 어떻게 하는 것이 좋나요 ?

**Comment by minkikim89** [comment]
@jhpark816 
현재 java-client에 키 개수 제약이 있는 부분이 없고, 간단히 살펴봤을 땐 c-client도 마찬가지로 보입니다.
이 상황에서 위에서 언급했듯 SetBulk, DeleteBulk에만 제약이 생기는 게 혼돈스럽고 버전 업그레이드에도 위험하므로, 간단하게 100 이상의 키를 사용할 시 너무 많은 키를 사용하고 있다는 로그 정도를 남기는 게 어떤가 싶습니다.

**Comment by jhpark816** [comment]
@minkikim89 
- 로그는 남기지 않아도 될 것 같습니다.
- 기존에 제공하던 bulk 연산에 대해선 제약 주는 것이 불가하네요.
- deleteBulk 연산만 처음 제공하기 때문에, 100개 제약을 주었으면 하는 데, 어떤 가요 ?
   - 안 주어도 되긴 하지만, 의견을 듣고 싶네요.
- manual 추가 해야 하고,
- bulk service API depricate 시키죠.

**Comment by minkikim89** [comment]
@jhpark816 
개인적으로는 deleteBulk 연산도 제약이 없는게 복잡하지 않은 것 같아서 나은 것 같습니다.

**Comment by jhpark816** [comment]
@minkikim89 
OK. 일관성을 위해 그렇게 하시죠.

참고로, bulkServiceLoopLimit 개념을 현재 bulk 연산에 구현할 수도 있습니다.
향후에 이 작업을 진행하죠.

**Comment by minkikim89** [comment]
https://github.com/naver/arcus-java-client/pull/251#event-3345578532 에서 bulkService 관련 API들 deprecate 시켰습니다.
이슈 close 합니다.
