### ISSUE TITLE
Operation Type 추가

### ISSUE THREAD

**Issue by whchoi83** [naver/arcus-java-client#22]
각 operation 에 read / write 를 구분할 수 있는 type 을 추가한다.

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <[arcus-java-client] Operation Type 추가 (#22)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-04-06 00:00 ~ 2015-04-10 23:59 GMT +09:00]<br>일본 출장 중입니다. 업무시간 중간 중간 대응 가능한 것은 대응하도록 하겠습니다. <br>급한 용무는 김진녕님에게 부탁드립니다.  <br>
--------------------------------------------

**Comment by whchoi83** [comment]
리뷰 부탁드립니다.
commit : https://github.com/naver/arcus-java-client/commit/0c90937e24e090e22a16228759829c8619c5f33a

**Comment by jhpark816** [comment]
리뷰 완료하고, 코멘트는 코드 쪽에 달았습니다.

**Comment by whchoi83** [comment]
수정해서 다시 commit 했습니다.

**Comment by whchoi83** [comment]
OperationType.java 코멘트 수정했습니다.

**Comment by jhpark816** [comment]
code review 완료

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [arcus-java-client] Operation Type 추가 (#22)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-04-06 00:00 ~ 2015-04-10 23:59 GMT +09:00]<br>일본 출장 중입니다. 업무시간 중간 중간 대응 가능한 것은 대응하도록 하겠습니다. <br>급한 용무는 김진녕님에게 부탁드립니다.  <br>
--------------------------------------------

**Comment by jhpark816** [comment]
merge 하였으므로, 이슈 브랜치는 제거해도 됩니다.
