### ISSUE TITLE
BulkSetWorker에서 정확한 실패 원인이 전달되게 수정.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#220]
BulkSetWorker의 awaitProcessResult() 메소드를 보면,
특정 set 연산이 실패할 경우에  END 응답을 전달하고 있다.
정확한 오류가 전달될 수 있게 수정되어야 한다.

```
    public void awaitProcessResult(int index) {
      try {
        boolean success = future.get(index).get(operationTimeout,
                TimeUnit.MILLISECONDS);
        if (!success) {
          errorList.put(
                  keys.get(index),
                  new CollectionOperationStatus(false, String
                          .valueOf(success), CollectionResponse.END));
        }
      } catch (Exception e) {
        future.get(index).cancel(true);
        errorList.put(keys.get(index), new CollectionOperationStatus(
                false, e.getMessage(), CollectionResponse.EXCEPTION));
      }
    }
```

**Comment by minkikim89** [comment]
현재 store 연산에 정의되어있는 OperationStatus에는 STORED 상태밖에 없는 상태입니다.
즉, client에서 정의하지 않은 응답을 캐시 서버가 돌려주지 않는한 store 연산이 success=false를 반환할 가능성이 없습니다.
만약 STORE가 아닌 다른 응답을 캐시 서버가 줄 경우 store 연산은 status에 해당 응답 메시지를 저장하지만, 여기서는 사용할 수 없는 상태입니다.
그래서, https://github.com/naver/arcus-java-client/issues/226 이슈를 먼저 검토하여 해결한 후에 이 이슈를 진행해야합니다.

**Comment by jhpark816** [comment]
현재 코드를 보면,
OperationStatus의 message를 "false" String으로 설정하므로 오류를 확인할 수가 없다.

```
                    if (!val.isSuccess())
                      failedResult.put(k, new CollectionOperationStatus(false, String
                              .valueOf(val.isSuccess()), CollectionResponse.END));
                  }
```

CollectionResponse에 해당 오류 응답을 추가하고,
아래와 같이 변경한다면 오류 메세지를 확인할 수 있다.

```
                    if (!val.isSuccess())
                      failedResult.put(k, new CollectionOperationStatus(val));
                   }
```

**Comment by minkikim89** [comment]
https://github.com/naver/arcus-java-client/pull/267 에서 bulkAPI들의 반환 타입을 OperationStatus로 반환하도록 변경하여 정확한 오류가 전달되는 상태입니다.
이슈 close 합니다.
