### ISSUE TITLE
Javadoc의 특수 기호 표현 방식 개선

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#221]
javadoc에서 generic 기호(`<>`)를 사용하면 HTML tag로 인식하는 문제가 있어,
`<` 문자는 `&lt;` 로 대체하고, `>` 문자는 `&gt;`로 대체하여 사용한다.

예를 들어 javadoc에서 `List<String> list = Collection.singletonList("list")` 라는 코드를 javadoc에 삽입하려고 하면, 아래와 같이 작성되어야 한다.
```
/**
 * <pre>
 * List&lt;String&gt; list = Collection.singletonList(&quot;list&quot;)
 * </pre>
 */
```

하지만, `@code`를 사용하면 특수 기호를 그대로 javadoc에 표현할 수 있다.
```
/**
 * <pre>{@code
 * List<String> list = Collection.singletonList("list")
 * }</pre>
 */
```

현재 arcus-java-client에서는 특수기호를 표현하기 위해 ampersand('&')로 시작하는 문자 코드를 사용하고 있으며, `@code` 를 사용하여 javadoc을 가독성있게 바꿀 수 있도록 수정한다.

참고 링크: https://reflectoring.io/howto-format-code-snippets-in-javadoc/

**Comment by minkikim89** [comment]
https://github.com/naver/arcus-java-client/pull/228 PR로 merge되었습니다.
이슈 close합니다.
