### ISSUE TITLE
key-value 연산들의 반환 타입 변경 검토

### ISSUE THREAD

**Issue by minkikim89** [naver/arcus-java-client#226]
현재 key-value 연산들의 반환타입은 Future<Boolean>으로,
Boolean값으로 단순 연산의 성공/실패 여부만을 확인할 수 있다.
이는 collection 연산들에서 오류 원인을 메시지로 주는 것과 차이가 있다.
이에 반환 타입을 변경하는 것을 검토한다.

**Comment by minkikim89** [comment]
@jhpark816 

반환 타입으로 OperationStatus를 사용하려고 했는데(현재 spymemcached가 사용하는 방식) 설계상 걸리는 부분이 있네요.
기존의 OperationStatus에 StatusCode를 삽입하고 OperationFuture 내에 OperationStatus를 삽입하여 응용에서 이를 확인할 수 있도록 설계하였는데 결국 이 방식이 CollectionFuture와 동일하네요. CollectionFuture의 경우 내부적으로 OperationStatus를 상속하는CollectionOperationStatus를 가지고 있습니다.
그래서, 결과적으로는 CollectionFuture를 키밸류연산에서 반환하는게 간단한 상황인데 이게 클래스 명탓에 키밸류 연산에서 사용해도 될지 의문입니다.
그렇다고 OperationFuture + OperationStatus 를 사용한다고 가정하면 CollectionOperationStatus는 기존 OperationStatus를 상속하여 StatusCode를 추가한 형태이기 때문에 이미 OperationStatus가 StatusCode를 가진 상태에서는 상속하여 사용하는 의미가 사라지게 되어 설계가 어색해집니다.

결과적으로, 아래 두 가지 방법
- CollectionFuture를 반환하도록 수정
- OperationFuture를 반환하도록 수정
중에 선택해야하는데 간단한 방법은 첫 번째 방식이지만 클래스명이 걸리는 상태이고,
두 번째 방식을 선택하면 CollectionFuture, CollectionOperationStatus의 설계가 조금 어색해지는 모습이 됩니다.

이에 대해서 의견주시면 감사하겠습니다.

**Comment by jhpark816** [comment]
@minkikim89 
OperationFuture 리턴하는 것이 맞다고 봅니다.

CollectionOperationStatus와 CollectionFuture는 향후 정리하는 것이 좋을 것 같습니다.
향후에 아래와 같이 정리하면 되는 가요 ?
- CollectionOperationStatus가 OperationStatus와 동일하면,
   - OperationStatus 사용하고 CollectionOperartionStatus는 deprecated.
- CollectionFuture가 OperationFuture와 동일하면,
   - OperationFuture 사용하고 CollectionFuture는 deprecated.

**Comment by minkikim89** [comment]
@jhpark816 
말씀하신대로 변경하는게 좋지만
CollectionFuture, CollectionOperationStatus를 deprecate 하려면
기존에 CollectionFuture를 반환하는 API들을 deprecate하고 
OperationFuture를 반환하도록 API를 새로 만들어야하는데
동일한 함수이름으로 다른 반환타입을 가지도록 API를 생성할 수 없기 때문에
이와 같은 변경이 불가한 상태입니다.

**Comment by jhpark816** [comment]
@minkikim89 
collection 연산에 대해 CollectionOperationStatus와 CollectionFuture 타입을
그대로 사용하는 방안 밖에는 없나요 ?

**Comment by minkikim89** [comment]
@jhpark816
조금 이상한 구현방식일 수 있지만,
OperationFuture과 OperationStatus가 각각 CollectionFuture와 CollectionOperationStatus를 상속하게 하여 구현할 수는 있을 것 같습니다. 이렇게 구현할 경우 Future는 간단하지만 CollectionOperationStatus 관련하여 구현 복잡성이 올라갈 수는 있습니다.(단순히 CollectionOperationStatus를 삭제하고 OperationStatus만을 두면 모든 status를 OperationStatus로 관리하면 되는데, 둘 모두 그대로 유지해야하므로)

**Comment by jhpark816** [comment]
@minkikim89 @hjyun328 
CollectionOperationStatus와 CollectionFuture의 향후 처리는 고민해 보도록 하고,
좋은 아이디어가 있으면 알려주세요.

**Comment by jhpark816** [comment]
@minkikim89 
아래 코멘트에서 어떤 API의 반환 타입을 변경하려 했던 건가요 ?

> 반환 타입으로 OperationStatus를 사용하려고 했는데(현재 spymemcached가 사용하는 방식) 설계상 걸리는 부분이 있네요.

**Comment by minkikim89** [comment]
@jhpark816 
그 부분은 예전 bulkService 구현에서 kv 연산들을 사용할 때 성공상태에 대한 값을 boolean 값으로 밖에 가져올 수가 없어서 이를 OperationStatus로 반환할 수 있게 하려고 한다는 뜻이었습니다. 해당 부분에 대해서 깊게 고민할 필요는 없고,
이 이슈는 그냥 모든 kv 연산에 대해서 return 값을 Future에서 OperationFuture로 변경하여 연산 실패 여부에 대한 자세한 내용을 OperationsStatus를 통해 확인할 수 있게 수정하려 한다고 보시면 됩니다.

**Comment by jhpark816** [comment]
@minkikim89 
asyncSetBulk() 메소드와 asyncDeleteBulk() 메소드의 현재 return type은 아래와 같습니다.
CollectionOperationStatus 대신 OperationStatus나 다른 OperationStatus로 변경하면 좋겠는 데,
이에 대해 가능한 방안을 다시 정리 부탁해요.

```
<T> Future<Map<String, CollectionOperationStatus>> asyncSetBulk(final List<String> key,
                                                                         final int exp, final T o,
                                                                         Transcoder<T> tc)
Future<Map<String, CollectionOperationStatus>> asyncSetBulk(List<String> key,
                                                                     int exp, Object o)
<T> Future<Map<String, CollectionOperationStatus>> asyncSetBulk(final Map<String, T> o,
                                                                         final int exp,
                                                                         Transcoder<T> tc)
Future<Map<String, CollectionOperationStatus>> asyncSetBulk(Map<String, Object> o,
                                                                     int exp)

Future<Map<String, CollectionOperationStatus>> asyncDeleteBulk(List<String> key);
Future<Map<String, CollectionOperationStatus>> asyncDeleteBulk(String... key);
```

**Comment by minkikim89** [comment]
현재 사용되는 kv 연산들의 반환 타입을 OperationFuture, OperationStatus를 사용하도록 수정하고 이후 bulk 연산들 수정하도록 하겠습니다.

**Comment by jhpark816** [comment]
@minkikim89 
"현재 사용되는 kv 연산들의 반환 타입을 OperationFuture, OperationStatus를 사용하도록 수정"은
구체적으로 어떤 작업을 말하는 것인가요 ?

**Comment by minkikim89** [comment]
모든 kv연산의 return 타입을 바꾸는 게 맞다고 생각하여 이 이슈를 처음에 생성했습니다. 예를 들어주신 set API로 예를들면,
```
  <T> OperationFuture<Boolean> set(String key, int exp, T o, Transcoder<T> tc);

  OperationFuture<Boolean> set(String key, int exp, Object o);
```
위와 같이 수정할 예정입니다. 이렇게 수정하여도 기존에 사용하던대로 Future 객체로 리턴된 내용을 받을 수도 있고, OperationFuture로 받을 경우에는 오류 원인도 확인할 수 있게 됩니다.
참고로, 내부적으로는 이미 OperationFuture를 사용하고 있지만 return 타입만 Future로 되어있는 상태입니다.

**Comment by jhpark816** [comment]
OK. 무슨 말인지 이해했습니다.
- OperationsStatus에 Response에 관한 정보를 추가하는 것이 먼저이지 않나요 ?

**Comment by minkikim89** [comment]
@jhpark816 
kv 연산 수정하고 함께 커밋하려고 생각하고 있었는데 따로 분리해서 하는게 좋겠네요.
말씀하신 부분부터 따로 PR하겠습니다.

**Comment by jhpark816** [comment]
@minkikim89 
OperationStatus 보강하고 bulk 연산 수정한 이후에 kv 연산의 반환 타입을 변경하면 좋겠습니다.
kv 연산의 반환 타입을 변경하는 것은 경우에 따라 다음에 릴리즈해도 되기 때문입니다.

**Comment by sUpniverse** [comment]
key-value 연산들에 반환 타입을 OperationFuture 형태로 진행하였고
[Key-Value Item](https://github.com/naver/arcus-java-client/blob/develop/docs/03-key-value-API.md#key-value-item) 을 통해 확인하 실 수 있습니다.
key-value 연산 중 asyncGet와 asyncBulkGet을 제외한 모든 연산에 대해 OperationFuture타입으로 변환 완료하였습니다.
그에 따른 테스트 코드들도 함께 추가하였습니다. [OperationStatusTest.java](https://github.com/naver/arcus-java-client/blob/develop/src/test/manual/net/spy/memcached/ops/OperationStatusTest.java) 이를 통해 오류 및 성공 여부를 확인하는 것을 볼 수 있습니다.
