### ISSUE TITLE
Bulk Service 동작 최적화 검토.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#229]
Bulk Service에서 awaitProcessResult() 동작 방식은 timed wait 방식을 사용하고 있다.
이 방식이 bulk service에 적합하지 않다고 본다.

예를 들어, 동시에 10개 연산을 수행할 수 있다고 가정한다.
- 처음 10개 연산을 요청한다.
- awaitProcessResult()는 첫째 연산부터 차례로 그 연산이 완료되기를 기다린다.
   - 완료되기를 기다리기 위해. future.get() 메소드를 이용한다.
   - 첫째 연산에서 timeout 발생한다면, 그 기간 동안 다음 연산을 요청할 수 없다.
   - timeout 발생하는 연산에 비례하여 전체 응답 시간이 길어진다.
- 이 방식 대신에 future.isDone() 메소드로 대기 없이
  해당 연산이 완료되었는 지를 검사하는 방식이 나을 것 같다.
   - 이 경우, 10개 중에 어느 하나라도 완료되면, 다음 연산을 요청할 수 있다.
   - 만약, 10개 모두 완료되지 않았다면, 첫째 연산에 대해 future.get()으로 대기해야 한다.

검토 바랍니다.

**Comment by minkikim89** [comment]
@jhpark816
말씀하신대로 수정하겠습니다.

**Comment by jhpark816** [comment]
@minkikim89 
이 설계가 최적인지 모르겠어요.
구현하면서 다른 아이디어가 생기면, 전달해 주세요.
여튼, bulk service thread가 non-blocking io로 동작해야 최적 성능을 낼 수 있다고 봅니다.

추가 이슈도 있습니다. 이 사항도 검토해 주세요.
- 여러 work thread들로 부터 N개의 bulk 연산 요청이 있는 경우,
- 현재는 1개 bulk 연산 처리를 마칠 때까지는 다른 bulk 연산을 처리하지 못합니다.
   즉, bulk 연산들을 1개씩 순차적으로 처리합니다.
   - 1개 bulk 연산 처리 과정에서 특정 memcached node와의 network 문제로 응답이 느리면
      결국 blocked io로 그 bulk 연산이 완료될 때까지 blocked 상태에 있게 됩니다.
   - 앞 bulk 연산에서 blocked 상태가 되므로, 그 후에 들어온 bulk 연산은 처리되지 못합니다.
- 현재 처리할 수 있는 다른 bulk 연산이 있다면,
    blocked 되지 않게 구현하는 방안을 찾아야 할 것 같습니다.

**Comment by minkikim89** [comment]
@jhpark816 
하나의 bulk service thread가 non-blocking io 처리를 어떻게 해야
최적인지는 아직 보는 중입니다.

하나의 bulk연산 처리 중 다른 bulk를 blocked되지 않게 하는 방안에 대한
현재 의견은 아래와 같습니다.
- 하나의 bulk연산을 처리하던 중 다른 bulk 연산을 확인하여
  block되지 않게 구현하는 방법은 현재 구현상으로는 생각하기
  어려운 상태입니다.
- 현재 구현상태는 bulk연산을 threadPoolExecutor에게
   blockingQueue로 넘겨 처리하고 있는 상태이기 때문에
  executor thread는 해당 연산을 마치고 나서 다음연산으로
  넘어가는 방법 이외에 다른 방법으로 변경하기 어렵습니다.
- 만약 이러한 최적화 방법을 구현하려면, threadPoolExecutor를
  사용하지 않도록 수정해야합니다. 
- threadPoolExecutor를 사용하면서 이와 같은 문제를 해결하려면
  현재 threadPool의 개수가 1로 설정되어있는데 이를 늘리면
  어느정도 해결할 수는 있는 상태입니다.

**Comment by jhpark816** [comment]
@minkikim89 
asyncBopInsertBulk()와 같이 threadPoolExecutor 사용하지 않는 방안이 나은 것 같습니다.
여튼, 2 방법을 비교하여 의견 주세요.

**Comment by minkikim89** [comment]
@jhpark816 
말씀하신대로 asyncBopInsertBulk와 같이 threadPoolExecutor을 사용하지 않는 방식이 나을 것 같습니다.
이와 같이 생각한 이유는 아래와 같습니다.
- threadPoolExecutor을 사용할 경우 같은 bulk 연산에 대해서 동시에 처리하지 못하고, 1개의 연산씩 처리가 되어야함
- bulk 처리 방식을 kv와 collection에서 동일하게 구현하는게 좋아보임

그런데, setBulk를 별개의 threadPoolExecutor를 사용하여 구현한 히스토리를 잘 모르겠는데
혹시 아시는 내용이 있으신가요?

**Comment by minkikim89** [comment]
https://github.com/naver/arcus-java-client/pull/242 PR로 threadPoolExecutor를 사용하지 않고,
기존 collection bulk 연산들과 마찬가지 방법으로 변경하였습니다.
이슈 close 합니다.
