### ISSUE TITLE
인터페이스 구현체의 interface 지정 이슈

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#23]
CollectionUpsertOperationImpl의 interface 지정이 아래와 같습니다.
CollectionUpsertOperation interface를 지정하도록 수정하는 게 좋을 것 같습니다.

참고 사항으로, CollectionStoreOperation와 CollectionUpsertOperation가 동일한 interface이기 때문에,
동작에는 문제가 없습니다.

```
public class CollectionUpsertOperationImpl extends OperationImpl implements
        CollectionStoreOperation {
    . . .
}
```

**Comment by jhpark816** [comment]
ExtendedBTreeGetOperationImpl도 interface 지정이 잘못 되어 있는 것 같습니다..
ExtendedBTreeGetOperation의 Callback interface는 
CollectionGetOperation의 Callback interface와 argument가 다른 데, 괜찮은가요 ?

```
public class ExtendedBTreeGetOperationImpl extends OperationImpl
    implements CollectionGetOperation {
    . . .
}
```

**Comment by whchoi83** [comment]
ExtendedBTreeGetOperationImple 의 instance 를 ArcusClient class 에서 생성하는데 이때 매개변수로 넘겨주는 Callback interface 의 구현을 부분을 보면 
ExtendedBTreeGetOperationImpl 은 ExtendBTreeGetOperation interface를 implements 하는 것이 맞습니다. 
해당 부분의 소스는 아래와 같습니다.
```java
	private <T> CollectionFuture<Map<ByteArrayBKey, Element<T>>> asyncBopExtendedGet(
			final String k, final CollectionGet<T> collectionGet,
			final boolean reverse, final Transcoder<T> tc) {

...
		Operation op = opFact.collectionGet2(k, collectionGet,
				new ExtendedBTreeGetOperation.Callback() {
					TreeMap<ByteArrayBKey, Element<T>> map = new ByteArrayTreeMap<ByteArrayBKey, Element<T>>(
							(reverse) ? Collections.reverseOrder() : null);
...
					public void gotData(String key, byte[] subkey,
							byte[] elementFlag, int flags, byte[] data) {
						assert key.equals(k) : "Wrong key returned";
						Element<T> element = new Element<T>(subkey, tc
								.decode(new CachedData(flags, data, tc
										.getMaxSize())), elementFlag);
						map.put(new ByteArrayBKey(subkey), element);
					}
				});
```

**Comment by whchoi83** [comment]
commit 완료 했습니다.
리뷰 부탁드립니다.
commit : https://github.com/naver/arcus-java-client/commit/ed4ef540c4e59966383d6fa2c3d81d7ecd348cf3

**Comment by jhpark816** [comment]
code reveiw & merge 했습니다..
이슈 브랜치는 제거해도 됩니다.
