### ISSUE TITLE
Switchover시 Operation 이동 검토

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#233]
클라이언트가 replication switchover를 인지할 수 있는 방법은 두가지다.

1. [operation을 read할 때 SWITCHOVER를 수신할 경우](https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/MemcachedConnection.java#L841-L845)
2. [ZK 이벤트의 캐시 리스트 변경 이벤트 수신](https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/MemcachedConnection.java#L395-L407) (ZK 이벤트 발생 후 다음 handleIO에서 인지하게 됨)

switchover를 인지하게 된 경우, 구 Master 노드의 readQ,writeQ,inputQ 에 존재하는 모든 Operation들을 구 Slave(신규 Master)로 이동하게 된다.

이때 1번의 경우에는 SWITCHOVER를 수신하게 되면 그 Operation는 서버에 반영이 되지 않았기 때문에 Operation을 구 Slave로 이동하는 것은 아무런 문제가 없다.

하지만 2번의 경우에는 문제가 발생한다. 
2번의 경우, readQ에 존재하는 Operation이 이미 서버에 반영이 되었다면, 해당 Operation이 구 Slave로 이동된 후 Operation이 한번 더 요청될 가능성이 존재한다. 따라서 아래와 같은 상황이 발생할 수 있다.

```
1. incr operation은 반영 완료되었고, readQ에서 읽지 못하여 제거가 되지 않은 상태.
2. ZK 이벤트의 노드 변경으로 인하여 switch over를 인지함.
3. 구 Master의 모든 operation을 신규 Master로 이동
4. 결국 incr operation은 두번 반영됨
```

2번 상황(ZK 이벤트의 캐시 리스트 변경 이벤트 수신)에 대해 Operation 이동 코드는 아래와 같다. 
이에 대해 검토가 필요하다.

https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/MemcachedConnection.java#L406

**Comment by hjyun328** [comment]
2번 상황에 대해 아래와 같이 재현을 해보았습니다.

```java
      System.setProperty("net.spy.log.LoggerImpl", "net.spy.memcached.compat.log.Log4JLogger");
      ConnectionFactoryBuilder f = new ConnectionFactoryBuilder();
      f.setOpTimeout(100000L);
      ArcusClient client = ArcusClient.createArcusClient("XXX.XXX.XXX.XXX:XXXX", "test", f);

      try {
        client.asyncIncr("a", 1, 0, 0);
      } catch (Exception e) {
        e.printStackTrace();
      }

      while (true) {
        Thread.sleep(1000);
      }
```

```
>>> Master
get a
VALUE a 0 1
0
END
replication switchover
OK
```

```
>>> Slave
get a
VALUE a 0 1
1
END
```

Increase Operation을 한번만 요청하였는데, Switch Over후 구 Slave에서 Operation이 한번 더 요청되는 결과가 발생합니다.

이 문제를 그대로 재현하는 것은 어렵기 때문에 Operation read보다 ZK 이벤트를 먼저 수신할 수 있도록 인위적으로 타이밍을 조절하여 테스트 하였습니다.

**Comment by hjyun328** [comment]
ZK 이벤트에서 switchover를 수신하는 경우,
아래의 코드에서 moveOperation 전에 setupResend를 먼저 호출하여 readQ의 operation을 제거하는 것이 맞을 것 같네요. 이에 대해서 검토 바라겠습니다.
https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/MemcachedConnection.java#L406

**Comment by jhpark816** [comment]
@hjyun328 
readQ에 write 연산이 존재하는 지를 검사하여 아래와 같이 처리할 수 있나요 ?
 - readQ에 write 연산이 존재하지 않으면,
   - master & slave 교체하고, 모든 연산을 이동 (기존과 동일)
- readQ에 write 연산이 존재하면,
   - 현재 replica group으로 write 작업은 중지
      - 새로운 연산은 들어올 수 있음.
   - readQ가 write 연산이 제거될 때까지 switchover 작업은 보류
      - write 연산의 응답으로 switchover 진행될 수 있음.
      - write 연산의 응답으로 switchover 진행되지 않았다면, switchover 진행

**Comment by hjyun328** [comment]
@jhpark816 
가능한것으로 보입니다.


> write 연산의 응답으로 switchover 진행되지 않았다면, switchover 진행

==> 이 부분은 readQ의 operation이 더 이상 남아있지 않을 때, switchover 응답을 받지 않은 경우, switchover를 진행한다는 건가요?

**Comment by jhpark816** [comment]
@hjyun328 
> write 연산의 응답으로 switchover 진행되지 않았다면, switchover 진행

이 부분은 readQ에 write 연산이 남아 있지 않을 때(read 연산이 있는 경우는 괜찮음),
switchover 진행한다는 의미입니다.
- read 연산만 남아 있는 경우는 "SWITCHOVER"나 "REPL_RESEND" 응답을 받지 않으므로,
  ZK 이벤트로 switchover 작업을 수행해야 하기 때문입니다.

**Comment by hjyun328** [comment]
@jhpark816 

제안해주신 아이디어에 대해 일부분 검토를 해보았습니다.

updateConnection에서 SWITCH OVER가 발생되면, 아래의 그림처럼 operation을 이동하게 되고, master만 socket write를 막은 상황입니다.

![스크린샷 2020-05-08 오전 11 55 37](https://user-images.githubusercontent.com/10741543/81365549-63a71a80-9123-11ea-9302-9bbf858bfe46.png)

여기서 한번 더 updateConnection에서 SWITCH OVER가 발생되면, B에서 A로 operation을 이동하게 되는데, 이때 이미 slave 쪽에서 writed 된 operation(r8)이 존재한다면, operation 순서를 맞추는 것이 의미가 없는 상황이네요.

![스크린샷 2020-05-08 오후 2 24 48](https://user-images.githubusercontent.com/10741543/81373420-b38fdc80-9137-11ea-86c6-fd546f3081b3.png)


두번째 그림에서 updateConnection이 발생되면, A 노드는 reconnect 처리를 해야 할 까요? 
두번 updateConnection이 발생될 동안, A노드의 readQ의 operation이 아직 처리되지 않아, disable 상태를 유지한다면, 네트워크 상의 문제가 있는 것으로 자체 판단하고, reconnect 함으로써 A의 readQ를 제거하면 operation 순서를 유지할 수 있을 것으로 보입니다.

**Comment by jhpark816** [comment]
@hjyun328 
- 짤리지 않은 그림 이미지를 올려 주세요.
- operation 순서 관점에서 정리하면,
  - master 노드로 보낸 연산들에 한하여 그들 간의 순서가 지켜져야 합니다.
  - slave 노드로 보낸 연산들에 한하여 그들 간의 순서가 지켜져야 합니다.
  - 하지만, master 노드와 slave 노드에 보낸 연산들 간에는 순서를 지키지 않아도 됩니다.
     - round robin 방식으로 master와 slave에 보낸 연산들은 그 순서가 지켜질 수 없기 때문에
       순서가 필요한 연산인 경우는 round robin 방식을 사용할 수가 없습니다.
  
위의 연산 순서를 참고하여, 다시 살펴봐 주세요.

**Comment by hjyun328** [comment]
현재 이슈의 대응 방안에 대해 정리합니다.

#### 1. readq 모든 operation을 신규 master로 이동 (기존 방식)
- idempotent 성격을 갖지 않는 operation(INCR, DECR, ...)의 경우 operation이 두번 반영되는 현상이 발생하므로 데이터의 정확성이 보장 되지 않음.
- INCR, DECR 작업의 정확성을 고려하고싶다면, 응용에서 CAS operation을 활용하도록 권장.

#### 2. readq의 idempotent 성격을 갖는 operation들을 cancel하고 모든 operation을 신규 master로 이동
- switchover시 아직 서버에 반영되지 않은 idempontent 성격을 갖지 않는 opreation들이 cancel되는 문제.

#### 3. 신규 slave의 readq에 남아있는 idempoetent하지 않는 operation을 모두 읽을 때까지 신규 master의 write operation 작업을 비활성화
- 슬라이드: [[arcus-java-client]_move_operation_v2.pdf](https://github.com/naver/arcus-java-client/files/4654053/arcus-java-client._move_operation_v2.pdf)
- PR: https://github.com/naver/arcus-java-client/pull/237
- 네트워크 상황이 좋지 않다면, 신규 slave의 read 작업이 지연되는 만큼, 신규 master의 write 작업도 지연됨. 신규 master로 요청된 operation들이 연쇄적으로 timeout이 발생 가능성이 있음.
- 신규 master의 write 작업을 활성화 하기 위한 로직이 추가됨. 이는 updateConnection의 모든 case에 대해서 고려해야 하므로, 코드가 복잡해지며, 테스트가 어려운 문제.

개인적으로 2번 방법이 나아보이며, 다른 좋은 아이디어가 있다면 제안 부탁드리겠습니다.

**Comment by hjyun328** [comment]
PR 반영되어 클로즈합니다.

https://github.com/naver/arcus-java-client/pull/430
