### ISSUE TITLE
불필요한 package 경로 제거 

### ISSUE THREAD

**Issue by whchoi83** [naver/arcus-java-client#25]
ArcusClient.java 에 보면 아래와 같이 CacheManger 를 생성할 때 net.spy.memcached 와 같이 package 경로를 사용하는 부분이 있습니다.

```java
	private static ArcusClientPool createArcusClient(String hostPorts, String serviceCode,
			ConnectionFactoryBuilder cfb, int poolSize, int waitTimeForConnect) {
...
		net.spy.memcached.CacheManager exe = new net.spy.memcached.CacheManager(
				hostPorts, serviceCode, cfb, latch, poolSize,
				waitTimeForConnect);
```
같은 package 내에 있고 다른 위치에서는 아래와 같이 package 경로를 사용하지 않고 있습니다.
```java
	static final int MAX_SMGET_COUNT = 1000; // server configuration is 2000.
	
	private CacheManager cacheManager;
```

기존 ArcusClient.java 의 위치가 다른 곳에 있었던 흔적이 아닐까 생각됩니다.
특별한 이유가 없다면 제거해도 무방할 것 같습니다.

**Comment by whchoi83** [comment]
제거한 후 commit 했습니다. 
사용하지 않는 import 도 함께 제거했습니다.

확인 부탁드립니다.
commit : https://github.com/naver/arcus-java-client/commit/fe161abaa71ee5a0fb0837ea4e6f2beeed514336

**Comment by jhpark816** [comment]
review 했습니다. 직접 merge 하시죠..

**Comment by whchoi83** [comment]
merge 완료 했습니다.
branch 제거하고 본 이슈는 close 하겠습니다.
