### ISSUE TITLE
Switchover move operation 동작 Operation 순서 검토

### ISSUE THREAD

**Issue by MinWooJin** [naver/arcus-java-client#253]
switchover 의 전체 동작은 아래와 같다.
1. replication group change Role
2. move operations. Master to Slave
3. Master node reconnect

이 중 1번과 2번. change role이 완료되고 move operations가 수행되기 전 응용의 작업 thread가
role change가 된 new master의 inputQ에 새로운 operation을 삽입할 수 있다.
결국, switchover move operation이 수행되면서 operation 순서가 보장되지 않을 수 있다.

old Master Node Operation Queue
- RQ : `Op1`
- WQ: `Op2, Op3, Op4`
- IQ :  `Op5, Op6`

move operation 도중 new Master InputQ에 insert

new Master Node Operation Queue
- RQ: ` `
- WQ: ` `
- Iq: `Op7, Op8, Op1, Op2, Op3, Op4, Op5, Op6`

순서를 보장할 수 있는 방법이 필요 할 것으로 보인다.

@hjyun328 
현재 작업중인 https://github.com/naver/arcus-java-client/issues/233 와 관련된 이슈로,
같이 검토가 필요할 것 같습니다.

**Comment by jhpark816** [comment]
여기에 한 가지 추가할 사항이 있습니다.
switchover 경우는 2가지가 있습니다.
- server response로 switchover하는 경우
   - operations을 먼저 이동한 후에 hash ring에서 change role 수행
- ZK 이벤트에서 switchover 확인한 경우
   - hash ring에서 change role 먼저 수행한 후 operations을 이동.

둘 다가 아래와 같이 수행되어야 할 것 같습니다.
- change role을 먼저 수행
- operations을 이동 : inputQ의 앞쪽으로 이동
   - Memcached IO thread가 수행하는 작업으로,
   - change role 이전에 inputQ에 있던 연산들은 모두 writeQ로 이동 시킨 상태이며,
     inputQ에 들어온 연산들은 아래 중의 하나임.
      - change role 이후에 들어온 연산
      - 순서 보장하지 않아도 되는 연산
  - 따라서, inputQ의 앞쪽으로 이동하면 문제가 없음.
- 고려 사항
  - 만약 이동해야 할 operations이 많다면,
     operations을 먼저 이동한 후에 change role을 수행하고,
     change role 직전까지 들어온 operations을 다시 이동하여야 하는 가 ?

참고로, 본 이슈는 #233 이슈와는 무과하게 처리하는 것이 좋겠습니다.

**Comment by minkikim89** [comment]
@jhpark816 
말씀하신 고려사항은 아래와 같은 이유로 구현하기 어려울 것 같습니다.
old master 노드에 있던 operation들을 모두 new master의 inputQ의 앞으로 옮긴 이후에
change role을 수행하고 다시 old master의 operation들을 옮긴다고 하면,
이 operation들은 new master inputQ의 중간에 들어가야합니다.
즉, old master가 첫 move 때 옮긴 operation 들을 순서대로 old-1,old-2,old-3이라고 하고 이를
new master의 inputQ에 옮긴다음 change role 후에 old master에 남아있는 old-4를 옮기려고 한다면
이미 new master에는 old-1, old-2, old-3, new-1, new-2와 같이 새로운 operation들을 받아둔
상태일 수 있어서 old-4를 중간에 끼워넣어야하는 상태가 발생하고 이 위치를 판단할 수가 없는 상태입니다.

**Comment by jhpark816** [comment]
@minkikim89 
그러면, change role 이후에 inputQ 앞쪽으로 옮기는 것이 현실적인 방안이고,
이렇게 수정하겠네요 ?

**Comment by minkikim89** [comment]
@jhpark816 
네 맞습니다. 수정해서 PR하도록 하겠습니다.

**Comment by jhpark816** [comment]
@minkikim89 
https://github.com/naver/arcus-java-client/pull/280/files PR과 관련성이 있어, 살펴보기 바랍니다.

**Comment by minkikim89** [comment]
@jhpark816 
간단할 줄 알았는데 문제가 있네요.
현재 inputQueue가 BlockingQueue를 사용하고 있는데
이 collection이 front에 element를 put하는 API가 없습니다.
해서, operation들을 앞에 넣는 것이 불가합니다.
이를 구현하려면 inputQueue를 BlockingDeque로 수정해야만 하는 상태입니다.
큰 문제는 없을 것으로 생각하는데 어떻게 생각하시나요?

**Comment by jhpark816** [comment]
@minkikim89 @hjyun328 @MinWooJin 
글쎄요. 여러 방안이 있을 것 같은 데, 의논해 보세요.
1.  inputQ에 있는 연산들을 tempQ에 받은 다음, inputQ로 add하고 tempQ에 있는 연산을 다시 inputQ에 add할 수 있습니다.
2.  BlockingDeque를 사용한다면, move 연산을 반대로 넣어야 하는 데, 이것 또한 쉽지 않을 것 같습니다.
3.  writeQ로 바로 넣을 수 있을 것 같습니다.

위의 1번과 3번이 낫지 않아 생각합니다.

**Comment by minkikim89** [comment]
@jhpark816 
1번의 경우는 중간에 client를 통해서 새로운 operation이 inputQ에 들어갈 수 있어서 불가합니다.
결국 3번 방법이 제일 낫겠네요.

**Comment by jhpark816** [comment]
@minkikim89 
client의 work thread는 addedQueue까지만 넣고
inputQueue에 넣는 것은 memcached io thread가 하는 걸로 알고 있어요.

**Comment by jhpark816** [comment]
@minkikim89 
writeQ에 바로 넣을 수 있다면, 그게 낫지 않나 생각해요.

**Comment by minkikim89** [comment]
@jhpark816 
아 맞네요. inputQueue에 바로넣는것으로 착각했네요.
두가지 중 검토해서 진행하겠습니다.

**Comment by jhpark816** [comment]
@minkikim89 
생각해 보니, inputQ가 empty 상태가 아닌가요 ?

**Comment by minkikim89** [comment]
@jhpark816 
switchover 할 때 slave의 inputQ 말씀하시는 건가요?
해당 inputQ는 조회 연산들이 들어갈 수 있지 않나요?

**Comment by jhpark816** [comment]
@minkikim89 
내가 잘못 알고 있었어요. work thread에 의해 inputQ에 연산이 들어갑니다.

```
  public void addOperation(final MemcachedNode node, final Operation o) {
    o.setHandlingNode(node);
    o.initialize();
    node.addOp(o);
    addedQueue.offer(node);
    Selector s = selector.wakeup();
    assert s == selector : "Wakeup returned the wrong selector.";
    getLogger().debug("Added %s to %s", o, node);
  }
```

그러면, 더 복잡해 지는 부분이
- inputQ를 writeQ에 옮길 때, writeQ에 넣을 수 있을 만큼만 이동하게 됩니다.
   즉, 잔여 연산이 남아 있을 수 있습니다. 가능성은  매우 희박하지만요.
- 잔여 연산이 inputQ에 없다면, writeQ로 바로 넣으면 되는 데,
- 잔여 연산이 inputQ에 있다면, writeQ에 바로 넣는 것이 문제가 됩니다.
- 잔여 연산과는 순서를 지키지 않아도 되는 가요 ? 
- 따라서, inputQ에 있는 연산들 중 move 연산은 경우에 따라

**Comment by minkikim89** [comment]
@jhpark816 
현재 이슈의 문제는
slave가 master로 change role을 한 이후에 inputQ로 들어오는 update 연산들이라고 생각합니다.
change role을 하기 전에 inputQ에 존재하는 연산들이 있을 수 있지만 이는 모두 조회 연산들이고,
change role을 한 이후에 들어오는 연산들은 모두 inputQ에서 대기하고 있을 것입니다.
그래서, 기존 master 연산들을 writeQ로 move 시킨다면 기존 slave 가 가지고 있던 조회 연산과는
순서를 지키지 않을 수 있지만 master가 된 이후 들어온 update 연산들과는 순서를 지킬 수 있으므로 괜찮다고 생각합니다.

**Comment by jhpark816** [comment]
@minkikim89 
결국, writeQ로 바로 넣거나, inputQ 앞으로 넣으면 되겠네요.

**Comment by minkikim89** [comment]
@jhpark816 
위에서 언급했듯 inputQ가 BlockingQueue이고 이 자료구조의 경우 앞에 넣는 API가 없기 때문에 inputQ의 자료구조를 변경하지 않는 한 writeQ에 바로 넣는 방법외에는 없는 상태입니다.
writeQ로 바로 넣을 경우의 문제는 바로 writeQ 가 가득차있을 경우입니다. 이 경우 writeQ 공간이 부족할 경우 writeQ에 이미 존재하는 operation들을 부족한만큼 cancel 하려합니다. writeQ는 linkedBlockingQueue로 되어있고, 이는 integer 최대 크기만큼 capacity를 잡아놓기 때문에 inputQ의 operation이 아무리 많아도 writeQ의 연산들을 cancel 시킨다면 모든 operation들을 move 시킬 수 있습니다.
검토부탁드립니다.

**Comment by jhpark816** [comment]
@minkikim89 
위 코멘트에서 writeQ full 이면, writeQ 연산들을 cancel 시킨다는 하는 데,
move할 연산을 cancel 시키지 않고 writeQ 연산을 cancel 시키는 이유는 무엇인가요 ?

**Comment by minkikim89** [comment]
@jhpark816 
move할 연산 read 혹은 update 연산들이며,
현재 change role 이후 inputQ에 있을 수 있는 update 연산보다 먼저 수행되어야하는 연산들입니다.
move할 연산들을 cancel 시킨다면 해당 연산들은 실행하지 못한 채 inputQ에 있는 update 연산들이
실행될 수 있습니다.
update 연산의 cancel과 실행 순서는 조금 조심스러워서 이러한 연산들은 최대한 살려두는 게
낫다고 판단했습니다. 반면, writeQ에 있는 연산들은 모두 조회 연산들이기 때문에 이를
cancel 하는게 좋다고 생각했습니다.

**Comment by jhpark816** [comment]
@minkikim89 
- writeQ full이면 2G 개의 연산이 있다는 의미이며,
  writeQ 뒤에 있는 연산들은 operation timeout 으로 cancel 될 것입니다.
- 따라서, writeQ full이면, move 연산을 cancel 시키면 됩니다.

결국, writeQ에 넣을 수 있을 만큼만 move 시키고 나머지 연산들은 cancel하면 됩니다.

**Comment by minkikim89** [comment]
operation을 move 시킬 때 writeQ로 move하고,
queue가 full 상태일 때는 cancel 시키도록 수정했습니다.
PR: https://github.com/naver/arcus-java-client/pull/286
이슈 close 합니다.
