### ISSUE TITLE
Unavailable cache node에 대한 요청 처리 점검.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#26]
Unavailable cache node에 대한 요청에 대해 어떤 응답을 줄 것 인지를 재검토하자.

**Comment by jhpark816** [comment]
@minkikim89 
오래전 이슈라 기억도 없습니다.
unavailable cache node라면, inactive cache node를 의미하는 것으로 생각되고,
이 경우는 현재 cancel 처리하고 있습니다.
따라서, 본 이슈에 관해 진행할 사항은 없다고 보입니다. 어떻게 생각하나요 ?

**Comment by minkikim89** [comment]
@jhpark816 
저는 이 이슈에 대해 아는 사항이 없습니다.
close 하셔도 될것 같습니다.
