### ISSUE TITLE
ArcusKetamaNodeLocator에서 upateHash 최적화.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#28]
updateHash()에서 node 제거 시,
arcus ketama locator config의 socketAddresses에서 그 node의 address 제거 작업을
여러번 호출하고 있는 데, 한번만 호출하면 됨.

**Comment by jhpark816** [comment]
commit link - https://github.com/naver/arcus-java-client/commit/3454d26e1277a48e5e14c02386007d8aa147007a

**Comment by whchoi83** [comment]
config.removeNode 를 한 번만 호출하는 것 보다 ArcusKetmaNodeLocatorConfiguration 을
DefaultKetamaNodeLocatorConfiguration 을 상속받는 형태가 아닌
KetamaNodeLocatorConfiguration 을 구현하는 형태로 바꿔 updateHash 를 최적하는 것이 더 좋을 것 같습니다.

updateHash 에서 remove 가 true 일때 기존 코드의 경우 loop 를 반복하면서
config.getKeyForNode 를 40번, config.removeNode 를 160번 수행하게 되는데. 
이 때문에 39번의 put 과 40번의 remove(시도 자체는 160번) 가 발생하게 됩니다. 
(getKeyForNode -> getSocketAddressForNode 에서 socketAddress 에 값이 없는 경우 put 수행)

KetamaNodeLocator 는 처음 KetamaHash 를 구성하고 나서 수정할 일이 없어서 기존 코드가 문제가 없었지만
ArcusKetamaNodeLocator 의 경우 updateHash 가 여러 번 호출 되는 경우가 발생하게 되어 문제가 있는 것 같습니다.

ArcusKetamaNodeLocatorConfiguration 을 상속구조가 아닌 구현으로 변경 후 
아래와 같은 방향으로 수정하는 것이 어떨까 합니다.
```java
private void updateHash(MemcachedNode node, boolean remove) {
	if (remove) {
		config.removeNode(node);
	} else {
		config.insertNode(node);
	}

	for (int i = 0; i < config.getNodeRepetitions() / 4; i++) {
		byte[] digest = HashAlgorithm.computeMd5(config.getKeyForNode(node, i));
		for (int h = 0; h < 4; h++) {
			Long k = ((long) (digest[3 + h * 4] & 0xFF) << 24)
					| ((long) (digest[2 + h * 4] & 0xFF) << 16)
					| ((long) (digest[1 + h * 4] & 0xFF) << 8)
					| (digest[h * 4] & 0xFF);
			if (remove) {
				ketamaNodes.remove(k);
			} else {
				ketamaNodes.put(k, node);
			}
		}
	}
}
```
기존에 getKeyForNode 를 통해 put 하던 구조를 없애고 명시적으로 insertNode 를 통해 put 을 하는게 더 좋을 것 같습니다.

**Comment by jhpark816** [comment]
Inherit는 그대로 하고,
아래와 같이 명시적으로 removeNode()와 insertNode()를 호출하는 것은 괜찮아 보이네요.

```java
private void updateHash(MemcachedNode node, boolean remove) {
	if (!remove) {
		config.insertNode(node);
	}
	for (int i = 0; i < config.getNodeRepetitions() / 4; i++) {
		byte[] digest = HashAlgorithm.computeMd5(config.getKeyForNode(node, i));
		for (int h = 0; h < 4; h++) {
			Long k = ((long) (digest[3 + h * 4] & 0xFF) << 24)
					| ((long) (digest[2 + h * 4] & 0xFF) << 16)
					| ((long) (digest[1 + h * 4] & 0xFF) << 8)
					| (digest[h * 4] & 0xFF);
			if (remove) {
				ketamaNodes.remove(k);
			} else {
				ketamaNodes.put(k, node);
			}
		}
	}
	if (remove) {
		config.removeNode(node);
	}
}
```

**Comment by whchoi83** [comment]
commit link - https://github.com/naver/arcus-java-client/commit/b6ac8157bcd9056e244a5e3c96312bb2ef7a76d4

**Comment by whchoi83** [comment]
merge 했습니다.
해당 브랜치 삭제하고 본 이슈는 close 하도록 하겠습니다.
