### ISSUE TITLE
새로운 노드 추가 시, connected 상태가 된 이후에 consistent hashing 참여시키는 방안 검토 및 구현.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#304]
새로운 노드 추가 시, 현재 동작은
- 그 노드에 대한 non-blocking connect 요청을 보내고 나서, 그 노드를 consistent hashing에 참여시키고 있다.
- 그리고, 어떤 응용 요청은 consistent hashing에서 새로운 노드로 mapping되어 그 노드로 요청을 보낼 수 있다.
-  그 노드는 아직 connected 상태가 아닐 수 있으며, 결국 inactive node로 인해 그 요청이 취소(cancel)될 수 있다.

해당 노드와의 연결이 완료된 이후에 consistent hashing에 참여시킨다면,
- cancel 없이 응용 요청을 처리할 수 있다.
- 그 노드가 아직 consistent hashing에 참여하지 않더라도 기존 노드에서 처리할 수 있다.
- 하나 염려되는 부분은
   - 여러 클라이언트에서 새로운 노드를 consistent hashing에 참여시키는 시점에서 차이가 커질 수 있는 지이다.
   - 이러한 시점의 차이가 크다면, 어떤 key가 mapping 되는 캐시 노드를 여러 클라이언트들이 서로 다르게 볼 수 있다.
   - 하지만, 시간이 지나면 eventually consistent하게 된다.

**Comment by minkikim89** [comment]
@jhpark816 
구현 방법은 이슈 내용에서 언급한 방법 외에 아래 방법까지 합해 두가지 방법이 있을 것 같습니다.
- connected 되지 않은 connection을 바로 hash ring에 투입하는 방법
  - 모든 새로운 connection은 connect 시도 후 바로 hash ring에 투입합니다.
  - 해당 connection에 operation을 요청할 때 isActive 확인 후 만약 inactive 상태라면
     reconnectAttempt 횟수를 확인하여 1이라면 아직 첫 번째 connect 시도
     상태이기 때문에 해당 connection의 큐에 operation을 삽입합니다. 만약 reconnect
     Attempt가 1보다 크다면 connect 시도가 잘 되지 않고 있다는 것이기 때문에
     cancel 처리합니다. 

개인적으로는 제가 정리한 내용으로 구현하는 것이 더 나을 것 같은데 어떻게 생각하시나요?

**Comment by jhpark816** [comment]
@minkikim89 
- "reconnectAttemp = 1"이 "새로운 추가된 캐시 노드로의 첫 번째 conect 시도"만을 의미하지는 않아요.
   기존 캐시 노드와 reconnect 하는 경우에도 "reconnectAttemp = 1"이 될 수 있습니다.
- Not-yet-connected 상태의 MemcachedNode를 hash ring에 투입하는 방안이
   connected 상태가 된 후에 hash ring에 투입하는 방안 보다 어떤 점이 나은가요 ?

**Comment by minkikim89** [comment]
@minkikim89 
- 기존 캐시 노드와 reconnect 하는 경우는 reconnectAttemp를 1로 설정하고,
   처음 캐시 노드와 connect 하는 경우는 0으로 설정하면 간단하게 구현할 수 있을 것 같습니다.
- connected 되지 않은 connection에 hash ring에 바로 삽입할 경우 hash ring을 바로 반영되기 때문에
  요청된 연산들이 다른 캐시 노드로 보내질 일이 없습니다. 현재 제안해주신 방법으로 구현할 경우 cancel은
  나오지 않지만 item들이 보내져야할 캐시 노드들로 보내지지 않아 캐시 노드로 전달되어도 결국 scrub 되게 됩니다.
- 단 연결이 완료되기 전에 큐에 연산들이 한꺼번에 몰리면 큐 오버플로우로 인한 cancel 이 발생할 수는 있습니다.

**Comment by minkikim89** [comment]
@jhpark816 
의견주시면 감사하겠습니다.

**Comment by jhpark816** [comment]
@minkikim89 @hjyun328 
- reconnectAttemp 값이 사용되는 기존 의미가 달라지면 어떤 영향이 있을 지를 판단할 수 있으면 좋겠습니다.
   - 참고로, 최신 spymemcached도 처음 MemcachedNode를 생성하는 경우에 reconnectAttemp를 1로 설정하고 있습니다.
- connected 상태가 된 이후에 hash ring에 반영하는 방법은
   - connected 되기 전까지는 기존 캐시 노드에서 저장, 조회가 이루어지므로 전혀 문제가 없습니다.
    새로운 캐시 노드로 mapping이 변경되는 시점이 connected 상태가 된 시점이라고 보면 됩니다.
   - 반면, connected 되기 전에 mapping이 변경되면 해당 연산이 제대로 처리되지 않는 문제가 발생할 수 있습니다.

**Comment by jhpark816** [comment]
@minkikim89 @hjyun328 
아래 사항을 참고 바랍니다.
- 새로운 캐시 노드를 hash ring에 참여시키는 시점이 모든 clients에서 동일해야 합니다.
   - connected 이후에 hash ring에 참여시키는 방안은 이 관점에서 걱정됩니다.
   - ZK 변경 이벤트를 받으면 바로 hash ring에 참여시키는 것이 더 안전한 것 같습니다.
- 따라서, connect 요청을 보내면, 바로 hash ring에 참여시키더라도
  해당 캐시 노드로의 operations은 받아들이는 방법을 잘 구현한다면, 이 방법이 나을 것 같습니다.

**Comment by jhpark816** [comment]
@minkikim89 
본 이슈는 완료된 상태이니, 요약 정리한 후에 close 바랍니다.

**Comment by minkikim89** [comment]
첫 번째 connect 시도일 때는 정상적인 노드일 확률이 높기 때문에,
operation을 cancel 하지 않고 queue에 삽입할수 있도록 수정하였습니다.
reconnect 시도라면 해당 노드는 현재 비정상인 상태일 확률이 높기 때문에
원래대로 cancel 처리를 합니다.
https://github.com/naver/arcus-java-client/pull/307 로 merge 되었으므로 close 합니다.
