### ISSUE TITLE
Future 객체들의 사용법에 대한 doc 정리

### ISSUE THREAD

**Issue by minkikim89** [naver/arcus-java-client#308]
현재 모든 연산들은 리턴값으로 Future 혹은 Future를 상속하여 구현한 객체를 리턴하고 있다.
이 중 BulkGetFuture의 경우 Future와 달리 추가적으로 getSome과 같은 함수를 제공하고 있다.
응용에서 이를 사용하면 상황에 따라 이득을 볼 수 있지만 이에 대한 가이드가 없어
대부분의 응용에서 단순히 Future로 리턴값을 받아 사용하고 있는 상태이다.
이와 같이 Future를 상속하여 구현한 클래스들을 모두 점검하여 만약 별개의 설명이 필요한 경우
doc에 추가하도록 한다.

**Comment by minkikim89** [comment]
https://github.com/naver/arcus-java-client/issues/226 이슈에서 키밸류 연산에 대한
리턴값이 바뀔 경우 이에 대한 내용도 포함되어야 한다.

**Comment by sUpniverse** [comment]
commit : #328 
- future의 get()과 getSome() API에 대한 arcus-future-get-API.md 작성
