### ISSUE TITLE
Immediate reconnect 시, readQ에 등록된 연산들에 대한 cancel 처리 최소화

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#313]
Java client는 asynchronous IO 방식으로 동작합니다.
Immediate reconnect(protocol mismatch 등이 원인) 해야 할 시점에 readQ에 다른 연산들이 존재할 수 있으며,
이러한 연산들을 모두 cancel 처리하는 것은 비합리적인 것 같습니다.

아래와 같이 개선 부분이 있는 것 같습니다.
- read 성격의 연산이면, writeQ 앞쪽으로 재등록
- write 성격의 연산이면, cancel 처리 (아래 2 경우를 구분하는 것이 불가하다고 생각됨)
   - cache server에 write 연산이 수행되었거나 수행될 경우 : cancel 메세지에 현재 상태 표현하면 좋을 듯.
   - cache server에 write 연산이 수행되지 않은 경우 (전체 ascii 명령이 아직 전달되지 않은 상태) : 재등록 가능.

참고 사항으로,
- C client는 synchronous IO 방식이므로, 다른 연산을 cancel 처리하는 경우가 없습니다.
   - Asynchronous IO 방식이더라도, 다른 연산에 미치는 영향을 최소화하도록 설계하는 것이 필요합니다.
- Cache server가 CLIENT_ERROR, SERVER_ERROR, ERROR 등의 응답을 보내는 즉시, client connection을 끊는 것은 적합하지 않다고 봅니다.
   - Client connection 끊는 것은 client에서 담당해야 한다고 봅니다.

**Comment by jhpark816** [comment]
@hjyun328 
본 이슈가 의미 있는 지를 먼저 검토하고, 의견을 주세요.

**Comment by hjyun328** [comment]
@jhpark816 

Operation 에러가 흔하지 않으며, 만약 에러가 발생된 경우라면 이미 정상적으로 클라이언트를 사용할 수 없는 상황이기 때문에, 코드 복잡성을 증가시킬 정도의 cancel 최소화를 위한 개선 작업이 필요한지에 대해서 의문입니다. 서버/클라이언트의 버그로 인한 프로토콜 에러나 서버의 internal 에러가 발생됐다면 Immediate reconnect 이후에도 ReadQ에 남아있는 Operation 에러는 여전히 발생할 확률이 높아보입니다. 오히려 기존 operation의 cancel을 최소화하기 보다는 빈번한 에러 발생 상황을 방지하기 위해 spymemcached처럼 에러 delay reconnet로 수정하는 것이 더욱 좋을 것 같다는 의견입니다.

**Comment by jhpark816** [comment]
@hjyun328 @minkikim89 

OK.
immediate reconnect가 아래 경우에 발생합니다.
대부분 전자의 경우에 발생할 것입니다.
- API 호출 시 잘못된 인자 값을 준 경우
- ARCUS client SW 오류

정확한 오류가 응용 로그에 기록되도록 하고요.
흔한 경우가 아니므로 본 이슈는 처리하지 않도록 합시다.
