### ISSUE TITLE
expire time 관련 travis ci 실패.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#314]
아래와 같은 expire time과 관련된 새로운 travis ci 실패 유형이 발생
- PipedBulkInsertMapWithAttrTest : [travis link](https://travis-ci.org/github/naver/arcus-java-client/builds/672388046)
  1. asyncGetattr() 로 Key 해당 item 없는지 검사
  2. expireTime 1초로 Map insert with create
  3. asyncGetattr() 로 서버의 Map attribute 검사
  4. sleep 1초
  5. mop get하고 결과가 null인지 검사 -> 오류 발생

- testMutateWithDefaultAndExp : [travis link](https://travis-ci.org/github/naver/arcus-java-client/builds/675703155)
  1. expireTime 1초로 incr, initial 값 3, expected 3
  2. 위와 동일하게 요청, expected 4 인데 실제로 3을 전달받음 -> 오류 발생
  -> 연속으로 incr 명령을 두번 수행하는데 그 과정에서
      1에서 수행했던 key가 expired 될 때 까지 두번째 명령이 서버로 전달되지 못한것으로 보임

travis ci 테스트 환경의 하드웨어 스펙으로 인해 item이 expire 되어 테스트가 실패한 것인지
아니면 또다른 문제가 있는지 검토가 필요하다.

**Comment by jhpark816** [comment]
@hjyun328 
본 이슈가 해결된 상태인 지를 살펴봐 주세요.

**Comment by hjyun328** [comment]
1. PipedBulkInsertMapWithAttrTest는 [이번 PR](https://github.com/naver/arcus-java-client/pull/317/commits/c9121a51b072e1c595b812a056add1303824be85)에서 sleep time을 1초 더 증가시켜 수정하였습니다. 따라서 expire time & sleep과 관련된 타이밍 이슈는 해결된 것으로 보이구요.

2. testMutateWithDefaultAndExp 테스트는 조금 이상하네요.  

assertEquals(4, client.incr("mtest", 1, 3, 1)); 코드에서 에러가 발생되는데, mtest가 다시 디폴트 값으로 초기화된 것으로 보아, 두번째 operation이 늦게 전송되었거나, 서버에서 늦게 수신되어 첫 번째 operation의 아이템이 제거된 이후에 처리된 것 같습니다. 말씀대로 테스트 장비의 리소스 문제가 있었던 것으로 판된됩니다.

```
  public void testMutateWithDefaultAndExp() throws Exception {
    assertEquals(3, client.incr("mtest", 1, 3, 1));
    assertEquals(4, client.incr("mtest", 1, 3, 1));
    assertEquals(3, client.decr("mtest", 1, 9, 1));
    assertEquals(9, client.decr("mtest2", 1, 9, 1));
    Thread.sleep(2000);
    assertNull(client.get("mtest"));
  }
```

**Comment by jhpark816** [comment]
2번 이슈는 "문제 없음"으로 결론내죠.
travis CI 환경에서 자주 발생한다면, 다시 고민해 보도록 합시다.
