### ISSUE TITLE
Operation의 노드 ReadQ 존재 확인에 대한 개선

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#315]
Node의 write buffer에 operation을 write하는 과정에서, 매번 readQ에 operation이 존재하는지 확인한다. 기본적으로 노드의 readQ의 구현체는 LinkedBlockingQueue이므로, readQ의 operation 확인 작업을 할 때 처음부터 순차 탐색을 해야 한다.

operation이 writing 상태로 전환될 때, readQ에 바로 삽입하여 operation을 확인하지 않도록 하거나, 별도의 자료구조를 사용해 readQ의 operation 확인 탐색 속도를 개선하도록 한다. 또는 최신 spymemcached 코드를 참고하여 개선한다.

https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java#L269-L275

**Comment by jhpark816** [comment]
@hjyun328 질문이 있습니다.
- 해당 operation을 처음 write하는 경우이면, readQ에 바로 추가해도 됩니다.
   - 즉, 새로운 자료 구조로 교체할 필요가 없다고 봅니다.
- 최신 spymemcached는 이 관점에서 어떤 최적화가 되어 있나요 ?

**Comment by hjyun328** [comment]
@jhpark816 

spymemcached는 writing 상태로 전환할 때 readQ에 바로 삽입합니다.

https://github.com/couchbase/spymemcached/blob/master/src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java#L249-L253

**Comment by jhpark816** [comment]
@hjyun328 그렇게 처리하시죠.

**Comment by jhpark816** [comment]
@hjyun328 @minkikim89 
PR을 보니, 질문이 하나 생깁니다.

WRITING 상태의 operation에 대해 아래와 같이 readQ 등록 여부가 달라집니다.
- 기존에서는 WRITING 상태의 op이더라도, 실제 write가 전혀 수행되지 않았다면 readQ에 등록되지 않게 됩니다.
- 변경에서는 WRITING 상태의 op이면 write가 전혀 수행되지 않았더라도, 무조건 readQ에 등록됩니다.

이러한 semantic 변화가 있어도, 기존 코드에 문제가 없는 지를 점검해야 하지 않나 생각합니다.
-  예를 들어, 기존 setupResend()에서 "Discarding partially completed op" 메세지와 같이
   write가 수행된 operation에 대해서만 cancel 처리하던 것이
   변경 코드에서는 실제 write되지 않은 operation도 cancel 처리하게 됩니다.

의견 주세요.

**Comment by hjyun328** [comment]
@jhpark816 

setupResend의 아래 코드를 말씀하시는건가요?
```
    while (hasReadOp()) {
      op = removeCurrentReadOp();
      if (op != getCurrentWriteOp()) {
        getLogger().warn("Discarding partially completed op: %s", op);
        op.cancel(cause);
      }
    }
```

위 코드의 의도를 파악해보면, 
완전하게 write가 된 operation(readQ에 있지만, writeQ에 없는 operation)들은 cancel 처리를 하고,
반대로 operation이 완전하게 write되지 않았다면(readQ에 있고, writeQ에 있는 operation - 이때는 current에 해당) cancel 처리하지 않고, 버퍼만 초기화해서 재연결 이후 다시 write 하도록 처리하는 것으로 이해하고 있습니다. 

따라서 변경 코드에서도 완전하게 writing 되지 않은 operation이 존재한다면, 그 operation도 위의 로직에 의해 cancel 처리가 되지 않을 것으로 판단이 되어 문제가 없을거라 생각됩니다. 제가 코드를 잘못 이해하고 있다면 지적 부탁드리겠습니다.

**Comment by jhpark816** [comment]
@hjyun328 
- 내가 코드를 잘못 보았네요. write가 완료된 연산만 cancel()하는 코드였네요.
- 그 외, 기존 코드에 문제가 될 만한 부분은 없었나요 ?

**Comment by hjyun328** [comment]
@jhpark816 

특별히 고려해야 할 부분은 setupResend 이외에 없다고 생각되네요. setupResend 코드도 예전에 최신 spymemcached 코드를 참고하여 pr을 보낸 기억이 있어서 현재 코드와 동일합니다.

**Comment by jhpark816** [comment]
@hjyun328 
OK. PR에서 변경 동작이 기존의 다른 부분에 영향을 미치는 부분이 없다고 알고 있겠습니다.

**Comment by hjyun328** [comment]
PR이 반영되어 클로즈 하겠습니다.
https://github.com/naver/arcus-java-client/pull/316
