### ISSUE TITLE
Set, Flush 연산 수행시 Local Caching 처리 이슈

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#329]
현재 클라이언트에서 get 연산에 대해서만 local caching을 하고 set, flush 연산에 대해서는 local caching 처리를 하지 않고 있다.

따라서 아래와 같은 문제가 발생할 수 있다.

1. KEY  "A"에 대해 get operation 
2. KEY "A"의 get 결과(VALUE="YYY")를 local cache에 저장
3. KEY "A"에 set operation(VALUE="ZZZ")
4. KEY "A"에 대해 get operation
5. local cache에서 KEY "A"의 결과를 얻음 (VALUE="YYY")

get 연산에 대해 local cache로부터 오래된 데이터를 반환하지 않도록, set/flush operation시 local cache 데이터를 갱신하거나, 제거하도록 한다.

**Comment by jhpark816** [comment]
@hjyun328 @sUpniverse 
이슈에 대한 의견입니다.
- set/flush 시에 local cache 변경/제거한다면, 최신 데이터를 유지할 수 있어 좋지만,
  set/flush 수행한 응용 서버에서의 local cache만 최신 데이터를 가지며, 
  다른 응용 서버의 local cache는 예전 데이터를 가집니다.
- local cache synchronization 이슈는 향후 고려 사항이며,
  설계에 따라 set/flush 수행 시의 local cache 갱신/삭제 방식을 사용하지 않을 수 있습니다.
- Local cache 성격 상 예전 데이터를 가져도 되고, 최적 성능을 내는 것이 중요합니다.

따라서,  set/flush 수행에서 local cache 갱신/수정 비용이 작고, 구현 코드가 아주 간단하다면,
이러한 구현의 추가를 고려해 볼 만하고,
그렇지 않다면, 이러한 기능을 추가하지 않아도 local cache 성격상 전혀 문제되지 않는다고 생각합니다.

**Comment by jhpark816** [comment]
@hjyun328 @sUpniverse 
마지막 코멘트에 대해 다른 이견 없이 동의하는 걸로 판단하여, 본 이슈는 close 합니다.
다시 논의해야 할 사항이 있다면, 다시 open 해 주세요.
