### ISSUE TITLE
Command pipeline response 처리 이슈.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#33]
현재 command pipeline response 처리 상의 아래 이슈가 있다.
- PIPE_ERROR string에 대한 handling이 없다.
  - PIPE_ERROR string을 받으면, 현재 operation을 완료하여야 한다.
- PIPE 연산으로 수행할 연산이 1개인 경우에 제대로 처리하여야 한다.

**Comment by jhpark816** [comment]
commit link: https://github.com/naver/arcus-java-client/commit/e1378d505bcb32db2900f479b22e9cfdba182fd1

**Comment by whchoi83** [comment]
코드에 검토사항 코멘트 추가했습니다.

**Comment by jhpark816** [comment]
Piped Stotre/Update 연산은 Exist 연산과 다르게
실패한 연산의 결과만 map에 담도록 되어 있어요.

**Comment by whchoi83** [comment]
아.... 제가 잘못 생각했네요. 
말씀하신데로 실패한 것들에 대해서만 결과를 리턴해주니까 기존 코드가 맞습니다.

commit 내용에 문제 없는 것 같습니다.

**Comment by whchoi83** [comment]
본 이슈는 완료 되었으므로 close 합니다.
