### ISSUE TITLE
Gets 연산의 Local Caching 추가

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#330]
gets, asyncGetsBulk 연산의 local caching 로직을 추가한다.

local cache에 gets 연산 결과를 저장할 때, CASValue(casId + value) type으로 데이터를 저장하지 않고, value만 저장하도록 한다. (CASValue를 local cache에 저장해버리면 get 연산을 수행 시 클래스 캐스팅 문제가 생긴다.)

**Comment by jhpark816** [comment]
@hjyun328 @sUpniverse 

gets 연산 의미를 다시 생각해 보니, local caching 하지 않는 것이 맞다고 봅니다.
이유는
- gets 연산은 cas 값 조회를 수반하므로, remote cache에서 반드시 조회해야 한다.
- get(getBulk 포함) 연산이 수행되는 key들과 gets 연산이 수행되는 key들이 서로 다를 것이라 예상한다.
- get 연산에 의해 local caching된 결과가 gets 연산의 local caching 시도에 의해 evict될 수 있다.
   - 결국, local caching 효과가 떨어진다.

**Comment by jhpark816** [comment]
@hjyun328 @sUpniverse 
gets 연산은 local caching 하지 않도록 하고, 본 이슈는 close 합니다.
혹 이런 결정이 문제가 된다면, 다시 open해 주세요.
