### ISSUE TITLE
sync api들의 timeout시 operation cancel 처리

### ISSUE THREAD

**Issue by sUpniverse** [naver/arcus-java-client#331]
sync API(내부에서 future.get 또는 latch.await하는 API - get, cas, incr, decr, ...)에서 timeout 이 발생하면, operation을 cancel 처리 하지 않도록 되어있다.

cancel처리가 되지 않을 경우 sync operation의 경우 operation이 서버로 write될 가능성이 있다.

arcus의 경우 cancel fail mode만을 지원하고 있기때문에 모든 sync api의 timeout이 발생했을때
operation에 대해 cancel처리 하도록 한다.

또한 이에대한 내용을 코드상에 코멘트 하도록한다.

**Comment by jhpark816** [comment]
@sUpniverse @hjyun328 
sync 성격의 API에서 Exception 발생 시에 cancel 처리하는 것이 맞는 방법인가요 ?
이 관점에서 한번 정리 부탁해요.

**Comment by sUpniverse** [comment]
대부분의 Operation은 이미 write 이후 readQ로 옮겨져 결과를 read할 상태로 대기하지만,
많은 양의 op가 아직 writeQ에 대기중일 시에 그중 하나의 operation에 대한 연산 결과에 timeout 발생시 cancel()을 해주는것은 아주 조금의 확률로 가능한 것이라고 생각합니다.
다만, syncAPI의 경우 async하지 않고 바로 해당 연산에 대한 결과가 도출이 되어야 하고, 해당 API 명에도 sync라고 명시적으로 쓰여있기때문에 timeout 발생시에는 조그마한 확률이라도 operation에 대한 cancel 처리는 하는것이 맞다고 생각합니다.
@jhpark816 

이 이유에 의해서 해당 작업을 진행했습니다.

commit : #332 
- syncAPI는 연산에 대한 결과가 즉시 도출되어야 하는 API이다. 따라서 API에 timeout이 발생했을 시 operation이 이미 write되었을 수도 있지만, 대량의 operation이 WriteQ에 있을 경우 아직 해당 operation이 write되지 않았을 확률이 조금 이라도 있기에 해당 operation에 대한 cancel()처리를 한다.
