### ISSUE TITLE
일부 Ascii Command가 UTF-8이 아닌 다른 character encoding으로 전송될 수 있는 문제

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#336]
java는 jvm 옵션(`-Dfile.encoding=UTF-16`)으로 default character set을 설정할 수 있다. default character set이 설정되면 String 클래스에서 byte array로 변환할 때 설정된 default character set에 따른 byte array로 인코딩된다. jvm 옵션을 설정하지 않을 경우 os의 system locale에 따라서 default character set이 설정된다.

만약 default character set이 UTF-16으로 설정될 경우, client를 시작할 때 아래의 에러가 발생된다. 

```
ERROR net.spy.memcached.protocol.ascii.VersionOperationImpl:  Error:  ERROR no matching command by net.spy.memcached.protocol.ascii.VersionOperationImpl@4211d9b7
WARN net.spy.memcached.MemcachedConnection:  Reconnection due to exception handling a memcached exception on {QA name=ArcusClient(4-8) for jam2in /x.x.x.x:11700, #Rops=1, #Wops=0, #iq=0, topRop=net.spy.memcached.protocol.ascii.VersionOperationImpl@4211d9b7, topWop=null, toWrite=0, interested=1}.
OperationException: GENERAL
	at net.spy.memcached.protocol.BaseOperationImpl.handleError(BaseOperationImpl.java:182)
	at net.spy.memcached.protocol.ascii.OperationImpl.readFromBuffer(OperationImpl.java:145)
	at net.spy.memcached.MemcachedConnection.handleReads(MemcachedConnection.java:781)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:720)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:240)
	at net.spy.memcached.MemcachedClient.run(MemcachedClient.java:2117)
```

위의 에러 로그처럼 Version Operation을 포함하여 일부 Operation command 들이 UTF-8 타입으로 전송되지 않고, JVM에서 default로 설정된 character set에 따라 encoding되어 전송되는 것 같다. UTF-16의 경우, 한 글자당 2byte로 전송되므로 캐시 서버에서 ascii command을 인식할 수 없어 에러를 반환한다.

이러한 현상을 막기 위해 현재 client에서는 KeyUtil 클래스를 제공하여 UTF-8로 강제 변환할 수 있도록 제공한다.

 https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/KeyUtil.java#L21-L27

Version Operation을 포함하여 모든 Operation 들이 default character set 설정과 무관하게 ascii command string이 항상 UTF-8 타입으로 서버에 전송될 수 있도록 변경한다.

**Comment by jhpark816** [comment]
@hjyun328 
본 이슈에 대해 어떻게 처리하는 것이 가장 합리적인지를 먼저 정리하시죠.

**Comment by hjyun328** [comment]
@jhpark816 
@uhm0311 

Jedis 클라이언트 기준으로 UTF-8로 강제 변환됩니다. 
[SafeEncoder](https://github.com/redis/jedis/blob/master/src/main/java/redis/clients/jedis/util/SafeEncoder.java#L27-L36)라는 클래스가 String <=> Byte 변환을 수행해주는데, 시스템의 character encoding과 상관없이 무조건 UTF-8로 변환해줍니다. SafeEncoder 키워드를 통해 대충 아래 코드로 확인하실 수 있습니다.

## String => Byte 변환 (Write시)
```java
public class Jedis {

  private final CommandObjects commandObjects = new CommandObjects();
 
  @Override
  public String get(final String key) {
    checkIsInMultiOrPipeline();
    return connection.executeCommand(commandObjects.get(key));
  }

}
```

```java
public class CommandObject {
  public final CommandObject<String> get(String key) {
    return new CommandObject<>(commandArguments(Command.GET).key(key), BuilderFactory.STRING);
  }

  protected CommandArguments commandArguments(ProtocolCommand command) {
    return new CommandArguments(command);
  }
}
```

```java
public class Connection {
  public <T> T executeCommand(final CommandObject<T> commandObject) {
    final CommandArguments args = commandObject.getArguments();
    sendCommand(args);
    if (!args.isBlocking()) {
      return commandObject.getBuilder().build(getOne());
    } else {
      try {
        setTimeoutInfinite();
        return commandObject.getBuilder().build(getOne());
      } finally {
        rollbackTimeout();
      }
    }
  }

  public static void sendCommand(final RedisOutputStream os, CommandArguments args) {
    try {
      os.write(ASTERISK_BYTE);
      os.writeIntCrLf(args.size());
      for (Rawable arg : args) {
        os.write(DOLLAR_BYTE);
        final byte[] bin = arg.getRaw();
        os.writeIntCrLf(bin.length);
        os.write(bin);
        os.writeCrLf();
      }
    } catch (IOException e) {
      throw new JedisConnectionException(e);
    }
  }
}
```

```java
  public static enum Command implements ProtocolCommand  /* interface ProtocolCommand extend Rawable */ {

    PING, SET, GET, GETDEL, GETEX, QUIT, EXISTS, DEL, UNLINK, TYPE, FLUSHDB, KEYS, RANDOMKEY, 
    ...

    private final byte[] raw;

    private Command() {
      raw = SafeEncoder.encode(name());
    }

    @Override
    public byte[] getRaw() {
      return raw;
    }
  }
```

```java
public class CommandArguments implements Iterable<Rawable> {

  private final ArrayList<Rawable> args;

  ...

  public CommandArguments(ProtocolCommand command) {
    args = new ArrayList<>();
    args.add(command);
  }

  public CommandArguments add(Object arg) {
    if (arg instanceof Rawable) {
      args.add((Rawable) arg);
    } else 
    ...
  }

  public CommandArguments key(Object key) {
    ...    
   else if (key instanceof String) {
      String raw = (String) key;
      processKey(raw);
      args.add(RawableFactory.from(raw));
    } 
    ...
    return this;
  }

  @Override
  public Iterator<Rawable> iterator() {
    return args.iterator();
  }
}
```

```java
public final class RawableFactory {

  public static Rawable from(String string) {
    return new RawString(string);
  }

  public static class Raw implements Rawable {

    private final byte[] raw;

    public Raw(byte[] raw) {
      this.raw = raw;
    }

    @Override
    public byte[] getRaw() {
      return raw;
    }
  }

  public static class RawString extends Raw {
    public RawString(String str) {
      super(SafeEncoder.encode(str));
    }
  }

}
```

## Byte => String 변환 (Read시)

```java
public class Connection {
  public <T> T executeCommand(final CommandObject<T> commandObject) {
    // commandObject = new CommandObject<>(commandArguments(Command.GET).key(key), BuilderFactory.STRING);
    ...
    if (!args.isBlocking()) {
      return commandObject.getBuilder().build(getOne());
    }
    ...
  }

  public Object getOne() {
    flush();
    return readProtocolWithCheckingBroken();
  }
}
```

```java
class BuilderFactory {

  public static final Builder<String> STRING = new Builder<String>() {
      @Override
      public String build(Object data) {
        return data == null ? null : SafeEncoder.encode((byte[]) data);
      }
  
      @Override
      public String toString() {
        return "String";
      }
  
  };

}
```

## SafeEncoder

```java
public final class SafeEncoder {

  public static volatile Charset DEFAULT_CHARSET = StandardCharsets.UTF_8;

  public static byte[] encode(final String str) {
    if (str == null) {
      throw new IllegalArgumentException("null value cannot be sent to redis");
    }
    return str.getBytes(DEFAULT_CHARSET);
  }

  public static String encode(final byte[] data) {
    return new String(data, DEFAULT_CHARSET);
  }
}
```

**Comment by hjyun328** [comment]
@jhpark816 @uhm0311 

지금까지 클라이언트 모듈에서 시스템의 character encoding과 관련한 이슈가 없었기 때문에(대부분의 시스템이 UTF-8을 기존 인코딩으로 사용하기 때문에), 코드 수정보다는 UTF-8 환경만 지원하도록 하는 것이 지금 상황에선 합리적인 것 같습니다. 

https://github.com/naver/arcus-java-client/pull/383 코드 리뷰에서 추가로 수정되어야 하는 코드가 상당히 많았었고, 수정한다 하더라도 테스트 코드 없이는 100% 정상 동작을 보장할 수 없을 것 같습니다. 테스트에 많은 시간 소모가 예상되기 때문에 지금으로서는 시스템의 인코딩을 바꾸는 방향으로 해결되어야 할 것 같네요. 이러한 인코딩 설정 관련 이슈가 있다는 것으로만 기억해두고, 요구가 있을 때 수정하는 것이 지금 상황에서 맞는 해결책인 것 같습니다.

다만, ascii command에서 최소한 UTF-8 Key의 길이를 byte 길이가 아닌 string 길이로 잘못 설정하는 경우는 없어야 할 것 같습니다. 이 부분은 인코딩 변경으로 해결될 수 없기 때문에, 코드 검토가 필요해보입니다. 자체적으로 코드 검토을 진행해보고 추가 코멘트 달도록 하겠습니다.

**Comment by hjyun328** [comment]
@jhpark816 @uhm0311 
코드 검토해보니 모든 operation의 key length 설정은 UTF-8로 잘 변환되고 있습니다.

**Comment by jhpark816** [comment]
@hjyun328 
java guide 문서에 시스템의 encoding 설정에 대한 주의 사항으로 추가하는 것으로 본 이슈를 정리하시죠.
그리고, 질문 사항은
- 일부 코드에서 UTF-8 encoding 하고 있어서 시스템 encoding 설정은 무조건 UTF-8로 설정해야 하는 거죠?
- C client에서는 string 바이트 자체를 저장하거나 조회하는 데, 결국은 system encoding 설정을 따르는 것으로 봐야 하죠?
- java client와 c client가 함께 캐시를 사용하려면, system encoding 설정만 맞추면 되는 거죠?

그리고, 나중에 문제가 된다면,
Jedis 처럼 safer encoding 기능을 두어 system encoding 무관하게 동작하게 할 수 있는 데요.
이 경우, c client와 java client가 동일한 캐시를 사용하게 하려면,
결국은 system encoding 설정을 맞추게 하고, systme encoding에 따른 바이트를 저장하고 조회해야 하지 않나요?

**Comment by hjyun328** [comment]
> 일부 코드에서 UTF-8 encoding 하고 있어서 시스템 encoding 설정은 무조건 UTF-8로 설정해야 하는 거죠?
java-client에서 Key, String Value가 UTF-8로 저장되므로, 시스템 encoding은 무조건 UTF-8이어야 합니다. 

> C client에서는 string 바이트 자체를 저장하거나 조회하는 데, 결국은 system encoding 설정을 따르는 것으로 봐야 하죠?
C Client의 Value는 byte array로 저장하므로, character encoding이 어떤 형식인지 알 수가 없습니다. value를 어떤 encoding으로 사용하느냐는 응용의 책임입니다. 다만 arcus-c-client를 사용하는 응용 코드상에 설정된 string key는 시스템의 character encoding을 따릅니다.

> java client와 c client가 함께 캐시를 사용하려면, system encoding 설정만 맞추면 되는 거죠?
C Client를 사용하는 응용에서 key와 value를 UTF-8로 저장할 수 있도록 변경해주어야 합니다. 

C에서는 String Type이 존재하지 않기 때문에 encoding을 신경쓸 필요 없을 것 같습니다. C Client를 사용하는 응용 쪽에서 신경써야한다는게 제 의견입니다.

**Comment by hjyun328** [comment]
https://github.com/naver/arcus-java-client/pull/387
PR에서 캐릭터 인코딩과 관련한 문서를 추가하였으므로, 이슈 클로즈 하겠습니다.
