### ISSUE TITLE
BulkStoreTest의 간헐적 테스트 실패

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#345]
TravisCI에서 BulkStoreTest 수행 중에 아래와 같이 간헐적으로 테스트가 실패가 발생한다.

![스크린샷 2021-05-07 오후 7 54 08](https://user-images.githubusercontent.com/10741543/117442453-bce19e00-af71-11eb-9b82-897eab9b26e6.png)

asyncBulkStore 연산이 모두 성공하고, Get 연산을 수행하면 아이템이 없다는 에러이다.

이 에러가 발생되는 원인을 파악하고 해결할 수 있도록 한다.

**Comment by hjyun328** [comment]
@jhpark816 

코드적으로 문제가 될만한 사항을 발견하지 못했습니다. 

set 직후 아이템이 존재하지 않는 현상이라면 의심해볼 수 있는 것은 3가지일 것 같은데요

- 병렬 테스트 문제
  - maven 설정(pom.xml)과, [travis test 명령어](https://github.com/naver/arcus-java-client/blob/master/.travis.yml#L13)를 보면 병렬 테스트와 관련한 어떠한 설정이 없기 때문에, 테스트 수행은 serial 하게 수행되는 것으로 보입니다. 따라서 병렬 테스트로 인한 item deleted, 다른 value로 overwrite되는 현상은 없다고 판단.
- item expired
  - expire time은 60초
  - timeout exception은 없었음
  - 테스트 코드에서 future wait을 수행하는데 최대 대기시간은 최대 20(set)+0.7(get)=20.7초. 시스템이 갑자기 느려짐에 따라 연산 수행이 늦어 expired 되는 현상은 없을 것이라고 판단
- item eviction
  - 현재로서는 확인 불가

일단 로컬 환경에서 테스트를 해보았는데 테스트는 실패하지 않습니다.

![스크린샷 2022-02-24 오후 3 49 26](https://user-images.githubusercontent.com/10741543/155473096-308a474b-bf92-4a28-bd31-ef9b36753b43.png)

새로운 CI 환경에서 이러한 현상이 한번 더 발생하게된다면 서버에 접속하여 eviction 수치를 확인해봐야 할 것 같습니다.


get item이 overwrite 됐는지, null 값인지 100% 확인할 수 없는 상황이라, 테스트 코드를 약간 변경해주어야 할 것 같습니다.

**before**
```java
      // GET
      int errorCount = 0;
      for (String key : keys) {
        String v = (String) mc.get(key);
        if (!value.equals(v)) {
          errorCount++;
        }
      }

      Assert.assertEquals("Error count is greater than 0.", 0,
          errorCount);
```

**after**
```java
      // GET
      for (String key : keys) {
        String v = (String) mc.get(key);
        Assert.assertEquals(key + " has invalid value", value, v);
      }
```

**Comment by jhpark816** [comment]
@hjyun328 
OK. test code 보강하고, 본 이슈는 close 하시죠.
errorCount 비교하는 테스트가 많은 데, 일괄 수정하면 좋겠습니다.

**Comment by hjyun328** [comment]
테스트 코드 보강은 반영되었습니다.
https://github.com/naver/arcus-java-client/pull/438

추후 CI에서 같은 현상이 발생시 재오픈하겠습니다.
