### ISSUE TITLE
ArcusClient 초기화시 CacheManager 동작 정리

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#350]
ArcusClient 초기화시 CacheManager 동작에 대해 정리한다.

현재 CacheManager의 초기화 동작에서 발생될 수 있는 문제는 아래와 같다.

- ArcusClientPool 생성시, CacheManager.commandCacheListChange (ZK의 `/arcus/cache_list/{serviceCode}` 경로의 watcher에 의해 호출되는 callback)가 호출이 될 때, 파라미터로 전달되는 children의 사이즈가 0이면(서비스코드의 캐시 노드가 존재하지 않는 상황), ArcusCilentPool 생성을 요청하는 쓰레드는 단 하나의 캐시노드가 클러스터에 추가될 때 까지 무한정 대기할 수 있다.

- 최초 hash ring 생성은 ArcusClientPool 생성을 요청하는 쓰레드(CacheManager.initZooKeeperClient)에서 생성되는 것이 아닌, ZK Watcher에 의한 별도의 쓰레드(CacheManager.commandCacheListChange)에서 생성된다. 따라서 아직 캐시 노드와 연결이 이루어지지 않은 상황에서 ArcusClientPool이 생성되며, 응용에서는 연결이 이루어지지 않은 노드에 request가 전송되는 상황이 발생될 수 있다.

**Comment by jhpark816** [comment]
@hjyun328 
본 이슈 처리는 완료된 상태이죠?
어떻게 수정했는 지를 정리 바랍니다.

**Comment by hjyun328** [comment]
> ArcusClientPool 생성시, CacheManager.commandCacheListChange (ZK의 /arcus/cache_list/{serviceCode} 경로의 watcher에 의해 호출되는 callback)가 호출이 될 때, 파라미터로 전달되는 children의 사이즈가 0이면(서비스코드의 캐시 노드가 존재하지 않는 상황), ArcusCilentPool 생성을 요청하는 쓰레드는 단 하나의 캐시노드가 클러스터에 추가될 때 까지 무한정 대기할 수 있다.

응용 시작 후, 처음 연결시 ZK로부터 비어있는 znode list를 얻어오고, 이를 통해 client 객체를 생성하면 IllegalArgumentException이 발생됩니다. Exception 발생시 메인 쓰레드의 clientInitLatch가 countdown이 되지 않아 무한 대기 하는 현상이었습니다. 
https://github.com/naver/arcus-java-client/pull/348  commit으로 처음 연결시 znode list가 비어있다면, client 객체를 생성하지 않고 clientInitLatch를 countDown 할 수 있도록 수정하였습니다.
