### ISSUE TITLE
[DOC] CollectionAttributes 사용법 정리.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#351]
ARCUS Java Client 사용자 가이드 문서에 CollectionAttributes 사용법을 추가합시다.

**Comment by jhpark816** [comment]
@sUpniverse 진행하시죠.

**Comment by jhpark816** [comment]
@sUpniverse 
오래 되어 기억나지 않는 데,
기존 문서에 어떤 문제가 있어 본 이슈를 등록하게 된 건지를 아나요?

**Comment by sUpniverse** [comment]
@sUpniverse 

별다른 문제 언급은 없었고, 이슈등록이 되어서 해당 문서 살펴보고 설명이 필요한 부분들을 추가하여 pr을 진행했습니다.

**Comment by jhpark816** [comment]
@hjyun328 혹 기억나는 것이 있나요?

**Comment by jhpark816** [comment]
PR(https://github.com/naver/arcus-java-client/pull/388) merge되어 close합니다.
