### ISSUE TITLE
Operation I/O 도중 Exception 발생시 노드 정보 출력

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#366]
operation I/O 도중 Exception이 발생될 경우, 메시지에 노드 정보가 포함되지 않아 logging level을 warn으로 설정하지 않으면 원인 파악이 어렵다.

TimeoutException 외의 다른 Exception이 발생하더라도 Exception 메시지에 노드 정보를 출력하여 어떤 노드에서 이슈가 발생하였는지 파악할 수 있도록 변경한다.

아래는 operation을 read하는 시점에서 연결이 끊어졌을 때 출력되는 메시지이다.
```
2021-07-15 13:53:37.235 WARN net.spy.memcached.MemcachedConnection:  Reconnecting due to exception on {QA name=ArcusClient(1-1) for test /1.2.3.4:11211, #Rops=0, #Wops=0, #iq=3, topRop=null, topWop=null, toWrite=0, interested=1}
java.io.IOException: Disconnected unexpected, will reconnect.
	at net.spy.memcached.MemcachedConnection.handleReads(MemcachedConnection.java:817)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:725)
	at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:246)
	at net.spy.memcached.MemcachedClient.run(MemcachedClient.java:2217)
```

**Comment by jhpark816** [comment]
@hjyun328 
위에 출력된 메세지를 보면, node 정보가 포함되어 있습니다.
현재는 log level이 warning  경우만 출력되므로, info인 경우도 위의 메세지가 출력되게 수정하자는 것인가요 ?

**Comment by hjyun328** [comment]
@jhpark816 
네. 맞습니다.

**Comment by SEONGMINY** [comment]
@hjyun328 @jhpark816 
log level 을 수정하는 것이 아닌 exception 메시지에 노드 정보를 출력해야할 것 같습니다.

**Comment by hjyun328** [comment]
@SEONGMINY @jhpark816 
제가 잠시 헷갈렸네요. 죄송합니다.
제 의도는 로그 메시지를 info level로 설정했을 때도 출력하자는 것이 아닌, 

exception message에 노드 정보를 추가하자는 것입니다. 어플리케이션에서 log level을 error로 설정하면, exception이 발생될 때 warn level의 로그는 출력되지 않으므로, 어떤 노드에 원인이 존재하는지 알 수가 없기 떄문입니다.

**Comment by SEONGMINY** [comment]
@jhpark816
형준 전임과 논의한 결과 3가지 방안이나왔습니다.

- Exception 메시지를 출력하는 곳에 노드 정보를 추가하며, Exception 메시지를 출력하지 않는 곳에는 한번 더 try catch로 감싸 Exception 메시지를 출력하도록 한다.
- Exception 메시지를 출력하는 곳에만 노드 정보를 추가한다
- log level을 수정하는 방안으로, 위험한 에러인 경우에만 log level을 error로 수정한다.

위 3가지 방안 중 어떠한 방안으로 진행하면 좋을지 조언 여쭙고 싶습니다.

**Comment by jhpark816** [comment]
@SEONGMINY @hjyun328 
어떻게 처리할 것인지 논의하여 결정하고 알려주세요.

**Comment by hjyun328** [comment]
@jhpark816 @SEONGMINY 

logger xml에서 java class 별로 log level을 설정할 수 있었네요.
응용에서 전체 log level을 바꾸지 않고, MemcachedConnection 쪽만 warn으로 설정하여 해결해도 될 것 같습니다.

```xml
<!-- 전체 로그 레벨 -->
<Root level="ERROR"> 
    <AppenderRef ref="console" />
</Root>

<!-- MemcachedConnection 로그 레벨 -->
<Logger name="net.spy.memcached.MemcachedConnection" level="WARN" additivity="false">
    <AppenderRef ref="console" />
</Logger>
```

**Comment by jhpark816** [comment]
@hjyun328 @SEONGMINY 
- 응용에서 logger 설정을 어떻게 변경하더라도 MemcachedConnection 관련하여 항상 WARN 이상의 로그를 출력하도록 디폴트 설정을 미리 해 두면 되나요 ? 이를 강제할 방안은 없는 거죠?
- 응용에서 logger 설정을 자유롭게 변경할 수 있으므로, 이 문제가 생기면 응용에 요청하여 설정을 변경하게 해야 하나요?

**Comment by hjyun328** [comment]
@jhpark816 

네. 응용에서 설정해주어야 합니다. 라이브러리에서 강제할 수 있는 방법은 없습니다.

**Comment by jhpark816** [comment]
@hjyun328 
logger 설정으로 해결하는 것으로 정하고, 이슈와 PR을 close 바랍니다.

**Comment by hjyun328** [comment]
https://github.com/naver/arcus-java-client/pull/367
PR 클로즈 하였고, 이슈 클로즈하겠습니다.
