### ISSUE TITLE
특정 key를 담당하는 cache node 찾을 시에 failure mode 고려 필요

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#4]
Key-to-node 찾을 시에 failure mode를 고려하고 있는 함수는 아래와 같다.
- MemcachedConnection의 addOperation()

Key-to-node 찾을 시에 설정된 failure mode를 고려하지 않고, redistribute 모드로 동작하는 경우가 있다.
- MemcachedConnection의 findNodeByKey()
-  asyncGetBulk()

위의 두 경우에서도 failure mode에 따라 특정 key를 담당하는 cache node를 찾도록 변경되어야 한다.

**Comment by jhpark816** [comment]
@hjyun328 현재 문제가 있는 지를 확인 바랍니다.

**Comment by hjyun328** [comment]
@jhpark816 

중복 코드로 보입니다.

https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/MemcachedConnection.java#L1028-L1084
https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/MemcachedConnection.java#L1250-L1295
https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/MemcachedClient.java#L1094-L1132

findNodeByKey에서 3가지(retry, redistribute, cancel) failure mode를 처리하고, 이 메소드를 재사용할 수 있도록 addOperation, asyncGetBulk 코드를 수정해야 할 듯 싶습니다.

**Comment by jhpark816** [comment]
@hjyun328 
- findNodeByKey()는 ARCUS 작업으로 들어간 메소드입니다.
- addOperation()과 asyncGetBulk()는 기존에 있던 코드인 데,
  여기서 중복 코드는 spymemcached에도 그대로 남아 있나요 ?
   spymemcahced 구현을 보고, 향후 수정 방향을 결정하였으면 합니다.

@minkikim89 @MinWooJin 
중요 사항으로 확인해 두기 바랍니다.

**Comment by hjyun328** [comment]
@jhpark816 

spymemcached에도 중복 코드가 존재하네요.

findNodeByKey 처럼 placeIn을 반환하는 코드를 메소드로 따로 분리해서 모든 코드에 재사용하고, cancel처리는 node에 직접 addOperation을 하게 될 때, 메소드 내부에서 cancel failure 모드를 확인하고, cancel 처리하는 것이 나아보입니다.

**addOperation**
https://github.com/couchbase/spymemcached/blob/master/src/main/java/net/spy/memcached/MemcachedConnection.java#L1217-L1248

**asyncGet**
https://github.com/couchbase/spymemcached/blob/master/src/main/java/net/spy/memcached/MemcachedClient.java#L1293-L1308

**Comment by jhpark816** [comment]
@hjyun328 
참고로, 응용에서 특정 key가 어떤 node에 매핑되는 지를 알고자 할 때,
"findNodeByKey() 메소드를 사용하세요" 라고 가이드하고 있음을 참고 바랍니다.

이 경우에도 적절한 메소드가 아닌 것 같고,
ArcusClient 또는 MemcachedClient 수준에서 이 기능을 제공하는 메소드를
따로 제공해 주는 것이 나을 것 같습니다.

**Comment by jhpark816** [comment]
@hjyun328 의견에 동의합니다.
- findNodeByKey와 같은 placeIn을 반환하는 코드를 메소드로 따로 분리하고, 모든 코드에서 이를 재사용
- cancel처리는 node에 직접 addOperation을 하게 될 때, 메소드 내부에서 cancel failure 모드를 확인하여 처리.

**Comment by hjyun328** [comment]
@jhpark816 
findNodeByKey와 유사한 메소드를 만들어 private를 두고 내부에서만 사용하게 만들어야 한다는 뜻인가요? 잘 이해를 못하겠습니다. 

우선 이에 대해 https://github.com/naver/arcus-java-client/pull/203 PR을 올렸으니 리뷰 부탁드립니다.

**Comment by jhpark816** [comment]
@hjyun328 
아래와 같이 진행 바랍니다.
- 현재 중복 코드의 제거 형태로 진행되고 있는 데, 중복 코드의 제거는 나중에 고려합시다.
- 본 이슈의 main 내용은 key에 대한 cache node를 찾는 방식에 관한 것이며, 
   이 부분에 문제가 있다면 그 이유를 설명해 주고, 나중에 PR 받겠습니다.

**Comment by hjyun328** [comment]
@jhpark816 
PR 업데이트 하였습니다. 
https://github.com/naver/arcus-java-client/pull/206

**Comment by jhpark816** [comment]
@hjyun328 
본 이슈의 현재 상태 및 향후 처리할 방향을 정리해 주세요.

**Comment by hjyun328** [comment]
@jhpark816 

spymemcached의 mget 연산에서 cancel failure mode를 고려하고 있지 않아,  지난번 이 주제로 회의를 했을 때 코드의 의도를 파악할 수 없어 이슈가 홀딩됐던 것으로 기억하는데요,

지금 java client에서 collection bulk 연산은 cancel failure mode를 고려하여 처리하고 있습니다. 물론 keyList를 node 별로 grouping한 다음, grouping된 keyList의 첫번째 key를 통해 다시 삽입할 node를 찾는 비효율적인 과정을 거치긴 합니다만(수정이 필요해보임), 아무튼 mget 연산도 bulk 성격의 연산이기에 cancel failure mode를 지원하지 못할 이유는 없다고 생각합니다. 

MemachedConnection에서 addOperation 메소드의 타입이 두가지가 있는데요,

Key를 통해 Operation을 삽입하는 메소드가 있고 `addOperation(key, op)`,
Node를 통해 Operation을 삽입하는 메소드`addOperation(node, op)`가 있습니다.

Operation의 cancel 처리는 `addOperation(key, op)`가 아닌 `addOperation(node, op)` 에서 처리하고,  
findNodeByKey 메소드에서 cancel, retry 모드일 때는 무조건 primaryNode로 리턴하여 수정하면 될 것 같습니다.

**Comment by jhpark816** [comment]
@hjyun328 
- collection bulk 연산 처리에서 비효율적 처리 부분은 별도 이슈로 올려주세요.
- failure mode 고려하여 memcached node 찾는 방식은 코드로 봐야 할 것 같습니다.
  - `addOperation(node, op)`에서 cancel 처리하려는 이유는 중복 코드 제거인가요?
  - 본 이슈에서 코드로 논의해도 되지만, PR로 논의하여도 됩니다.

**Comment by hjyun328** [comment]
https://github.com/naver/arcus-java-client/pull/386
PR이 반영되어 이슈 클로즈합니다.
