### ISSUE TITLE
CollectionExistOperationImpl에서 command buffer 크기 설정 검토.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#400]
CollectionExistOperationImpl 클래스의 initialize() 메소드를 보면, command buffer 크기 설정이 이상합니다.
확인하고 수정 바랍니다.

```java
  @Override
  public void initialize() {
    String args = collectionExist.stringify();
    byte[] additionalArgs = collectionExist.getAdditionalArgs();
    ByteBuffer bb = ByteBuffer.allocate(null == additionalArgs ? 0 : additionalArgs.length +
            +KeyUtil.getKeyBytes(key).length
            + KeyUtil.getKeyBytes(subkey).length
            + args.length()
            + OVERHEAD);
    setArguments(bb, collectionExist.getCommand(), key, subkey,
            null == additionalArgs ? 0 : additionalArgs.length, args);

    . . .
  }
```

**Comment by jhpark816** [comment]
initialize() 메소드의 로직 자체도 검토 바랍니다.

**Comment by SEONGMINY** [comment]
아래와 같이 initialize 메소드를 변경하였습니다.

```java
@Override
  public void initialize() {
    byte[] additionalArgs = collectionExist.getAdditionalArgs();
    ByteBuffer bb = ByteBuffer.allocate(KeyUtil.getKeyBytes(key).length
            + additionalArgs.length
            + OVERHEAD);

    setArguments(bb, collectionExist.getCommand(), key, additionalArgs.length);

    bb.put(additionalArgs);
    bb.put(CRLF);

    ((Buffer) bb).flip();
    setBuffer(bb);

    if (getLogger().isDebugEnabled()) {
      getLogger().debug("Request in ascii protocol: "
              + (new String(bb.array())).replaceAll("\\r\\n", ""));
    }
  }
```

```additionalArgs```와 ```args``` 는 데이터와 데이터 길이를 나타내기 때문에, ```args```를 지우고  ```args```를 ```additionalArgs.length```로 표현하였습니다.

다음으로 제거한 것은 ```subkey```입니다. ```CollectionExistOperationImpl```이 사용되는 Collection은 Set으로 Set Exist는 아래와 같이 ```subkey```를 필요로 하지 않기 때문에 제거하였습니다.

```sop exist <key> <bytes> [pipe]\r\n<data>\r\n```

그 다음 변경한 것은 ```additionalArgs``` null 체크하는 부분을 변경하였습니다. ```additionalArgs```의 값이 null인 경우 아래와 같이transcoder에서 NullPointerException 에러를 리턴하기 때문에 따로 null 체크를 하지 않아도 된다고 판단되어 변경하였습니다.

![image](https://user-images.githubusercontent.com/58216191/149467626-d7b4d678-dfb9-450f-8418-1f7b9810e456.png)

(OVERHEAD의 argument는 command("sop exist"), data.length, ' '(space), CRLF 로 OVERHEAD 32를 넘지않을것으로 판단되어 따로 변경하지 않았습니다.)

**Comment by jhpark816** [comment]
수정하였으므로, close 합니다.
