### ISSUE TITLE
Switchover시 moveOperation, changeRole 순서 검토

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#402]
Switchover 발생 시,

1) ZK로부터(`MemcachedConnection.updateReplConnections`) 이벤트를 받을 경우,
아래의 코드에 따라 먼저 복제 그룹 멤버의 role을 변경한 후,  Old Master의 Operation들을 New Master로 이동한다. 

https://github.com/naver/arcus-java-client/blob/2e5135cba99584657a1d26e62026693f8adc0fbd/src/main/java/net/spy/memcached/MemcachedConnection.java#L458-L464
https://github.com/naver/arcus-java-client/blob/2e5135cba99584657a1d26e62026693f8adc0fbd/src/main/java/net/spy/memcached/MemcachedConnection.java#L509-L515

2) 하지만, ZK가 아닌, Old Master 서버로부터 "SWITCHOVER", 응답을 먼저 받을 경우, 
아래 코드에 따라 Old Master의 Operation들을 New Master로 이동한 후, 복제 그룹 멤버의 role을 변경한다.
https://github.com/naver/arcus-java-client/blob/2e5135cba99584657a1d26e62026693f8adc0fbd/src/main/java/net/spy/memcached/MemcachedConnection.java#L556-L563

2번의 경우, 복제 그룹 멤버의 role을 변경하기 전, 클라이언트에 의해 Old Master로 요청이 들어올 수 있다. 이 Operation들은 무조건 "REPL_SLAVE ${NewMasterAddress}"응답을 받게 된다. 만약 이 상태에서 "REPL_SLAVE" 응답을 받는다면, slave에 Master Candidate(NewMaster)가 존재하지 않아, 아래의 코드에 따라 Error 로그가 출력되며, Operation의 상태가 UNDEFINED로 설정된다. 게다가 Operation이 New Master로 moving 되지도 않는다.

https://github.com/naver/arcus-java-client/blob/2e5135cba99584657a1d26e62026693f8adc0fbd/src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java#L141-L147

현재 코드에서 Master candidate가 null인 상황은 사실 정상적인 동작이었으며, `BaseOperationImpl`에서 Error 로그를 출력하지 않고, Operation을 New Master로이동할 수 있도록 Operation을 `Complete` 상태가 아닌 `Moving` 상태로 전환하는 것이 필요하다. 

아니면 BaseOperationImpl 코드를 그대로 두고, 2번의 케이스가 발생될 때 moveOperation의 순서를 조정하는 것이 근본적인 해결책일 수 있을 것 같다. 기존 코드의 의도를 먼저 파악해야하므로 문제가 없는 것을 충분히 검증한 후 수정할 수 있도록 한다.

**Comment by hjyun328** [comment]
@sUpniverse 

master candidate를 찾을 수 없는 경우, 이전 master candidate 참조 정보를 이용하네요.
만약 candidate를 찾을 수 없다면 null로 할당해야 할 것 같습니다.

https://github.com/naver/arcus-java-client/blob/2e5135cba99584657a1d26e62026693f8adc0fbd/src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java#L133-L135

**Comment by jhpark816** [comment]
@hjyun328 
master candiate를 찾을 수 없다면 null로 설정해야 하는 이유를 풀어서 설명 부탁합니다.

**Comment by sUpniverse** [comment]
코드가 반영되어 issue close합니다.
