### ISSUE TITLE
SMGetTrimmKey, SMGetElement의 compareTo 검토

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#412]
SMGetTrimKey의 생성자에서 bkey가 long type이면 bytebkey가 null이 할당된다.

```java
 public SMGetTrimKey(String key, Object bkey) {
    this.key = key;
    if (bkey instanceof byte[]) {
      this.bytebkey = new ByteArrayBKey((byte[]) bkey).getBytes();
      this.bkey = -1;
    } else {
      this.bkey = (Long) bkey;
      this.bytebkey = null;
    }
  }
```

compareTo 메소드에서 bytebkey가 null이면, long type의 bkey를 다른 bkey(`getBkey()`)하고 비교를 하는데
```java
  @Override
  public int compareTo(SMGetTrimKey param) {
    assert param != null;

    int comp;
        /* compare bkey */
    if (bytebkey == null) {
      comp = Long.valueOf(bkey).compareTo(param.getBkey());
    } else {
      comp = BTreeUtil.compareByteArraysInLexOrder(bytebkey, param.getByteBkey());
    }

    /* if bkey is equal, then compare key */
    if (comp == 0) {
      comp = key.compareTo(param.getKey());
    }

    return comp;
  }
```

bkey가 -1이면 IllegalStateException이 발생된다. 
```java
  public long getBkey() {
    if (bkey == -1) {
      throw new IllegalStateException("This element has byte[] bkey. " + toString());
    }
    return bkey;
  }
```

bkey는 unsigned long type이므로 -1(18,446,744,073,709,551,615) 값을 가질 수 있다. long type의 bkey를 사용하는 상황에서 getBkey()를 호출할 때 Exception을 던져선 안된다. 

SMGetTrimmKey, SMGetElement 클래스의 코드를 수정한다.

**Comment by jhpark816** [comment]
@hjyun328 
기존에 숨어 있던 버그죠?

**Comment by hjyun328** [comment]
@jhpark816 
코드에서는 longkey의 -1 값을 byte array type이라고 정의하였기 때문에, 버그라고 할 수 있겠네요.
long key, byte array key 필드를 따로 두지 않고, 이 두 필드를 묶은 BKeyObject 클래스를 사용하여 수정해야 할 것 같습니다.

**Comment by hjyun328** [comment]
@jhpark816 
사용자가 long key를 음수로 설정하였고, 클라이언트 코드의 bkey validation checking에서 음수인 long key일 때 exception을 발생시켰다면 버그가 아닙니다.

**Comment by hjyun328** [comment]
@jhpark816 
다시 생각해보면, 개발자가 long type이 signed type이라는 것을 알고 있기 때문에
long bkey에 음수를 설정하여 사용하지 않을 것 같습니다. 
bkey validation checking에서 long key가 음수라면 그냥 exception을 던지는게 좋을 것 같다는 생각이 듭니다.

signed long 범위를 벗어나는 API를 사용하겠다면, 차라리 API 쪽에서 unsigned long type를 받을 수 있는 API를 추가하는 것이 맞는 방향인 듯 합니다.

**Comment by sUpniverse** [comment]
#424 에 issue 반영되어 close 합니다.
