### ISSUE TITLE
long type bkey의 특성 문서화

### ISSUE THREAD

**Issue by sUpniverse** [naver/arcus-java-client#419]
현재 arcus-java-client에서는 long type의 bkey는 singed 형태로 양수 부분만이 사용가능하다.
또한 내부 코드에서는 null 일 경우에 -1을 반환하고 있다. 

이런 특수한 상황을 문서에 기록하여 사용자로 하여금 혼란이 없도록 한다.

또한 추가될 사항들도 고려하여 문서를 추가한다. (예. 음수 값을 설정시 Exception 발생 등)

**Comment by jhpark816** [comment]
@sUpniverse 
API를 통해 singed long을 받더라도,
내부 코드에서는 null 나타내기 위해 long 타입 대신 Long 타입을 사용하였으면 합니다.
이렇게 수정 가능한 지를 확인해 주기 바랍니다.

**Comment by sUpniverse** [comment]
@jhpark816 
현재 bkey를 long형태의  primitive type으로 사용하는 내부의 구현은 BTreeSMGetWithLongTypeBkeyOld, SMGetElement, SMGetTrimKey 에서 사용하고 있습니다. 이를 Long 형태로 바꾸는데는 문제가 없을 것 같습니다.

또한 bkey를 get하는 부분이 아래와 같이 일부 구현이 되어 있는 되어 있는 부분이 있습니다.
long bkey와 byte bkey를 함께 사용하는 코드에는 bkey 획득시에 아래와 같이 모두 구현하도록 하겠습니다.

https://github.com/naver/arcus-java-client/blob/832dea35923fbfd15d79107ef6e5a5dd1039c050/src/main/java/net/spy/memcached/collection/SMGetElement.java#L95-L108

**Comment by jhpark816** [comment]
@sUpniverse @hjyun328 
bkey 관련 사항을 정리합니다.

- API 수준에서는 `long` 타입 bkey 제공합니다.
   - API 수준에서는 음수, 0, 양수 모두를 사용할 수 있습니다.
   - 하지만, cache server에서 ascii protocol에서는 음수를 허용하지 않으므로,
      API 수준에서 음수는 사용할 수 없도록 하고, 가이드 처리한다.
- 내부 구현에서 long bkey 값을 저장하기 위해 `Long` 타입을 사용합니다.
   - long bkey와 byte array bkey 필드를 두어 bkey 값을 보관하므로,
     어느 하나는 정상적인 값을 다른 하나는 null 값을 가지게 됩니다.
   - long bkey 값이 null인지를 구분하기 위해 Long 타입 사용할 필요가 있습니다.

위의 형태로 구현하고, API로 제공하면 되는가요?

**Comment by sUpniverse** [comment]
@jhpark816 @hjyun328 

네 정리해 주신 사항이 맞습니다.

다만, 추가 적으로 논의되어야 할 사항이 있습니다.

현재 내부 구현에서 long bkey와 byte array bkey를 class로 담아서 한번에 저장하는
[BkeyObject](https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/collection/BKeyObject.java)도 사용이 되고 있습니다.

```java
public class BKeyObject {

  public enum BKeyType {
    LONG, BYTEARRAY, UNKNOWN
  }

  private BKeyType type = BKeyType.UNKNOWN;
  private Long longBKey;
  private ByteArrayBKey byteArrayBKey;

  public BKeyObject(long longBKey) {
    setLongBKey(longBKey);
  }

  public BKeyObject(byte[] byteArrayBKey) {
    setByteArrayBKey(new ByteArrayBKey(byteArrayBKey));
  }
```

생성시에 long type 혹은 byte array type으로 생성자를 통해서 초기화를 하고
Enum으로 type값을 지정합니다.

```java
public ByteArrayBKey getByteArrayBKey() {
    if (BKeyType.BYTEARRAY == type) {
      return byteArrayBKey;
    } else {
      return null;
    }
 }

  public byte[] getByteArrayBKeyRaw() {
    if (BKeyType.BYTEARRAY == type) {
      return byteArrayBKey.getBytes();
    } else {
      return null;
    }
  }
```

또한 값을 가져올 때는 type으로 확인 한뒤, 해당 type을 경우엔 값을 아닐 경우엔 null을 반환합니다.

현재 사용되는 부분은 아래와 같습니다.
- [BTreeFindPosition](https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/collection/BTreeFindPosition.java), [BTreeFindPositionWithGet](https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/collection/BTreeFindPositionWithGet.java), [BTreeGetByPosion](https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/collection/BTreeGetByPosition.java), [BTreeInsertAndGet](https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/collection/BTreeInsertAndGet.java)

이렇게 어떤 부분은 long bkey와 byte array bkey를 병합으로 사용하는 곳도 있고, 또 다른 부분은 위와 같이 BkeyObject를 사용하는 부분이 있어 일관성을 위해 통일이 필요해 보입니다.
- long type, byte array type 두개의 필드를 모두 사용할 경우
  - BkeyObject 혹은 
  - long type, byte arrary type 두개의 필드 사용
- long type, byte array type 한개의 필드만 사용할 경우
  - long type
    - `Long`으로 사용
  - byte array type
    - 이전과 동일하게 사용

**Comment by jhpark816** [comment]
@sUpniverse @hjyun328 
- BKeyObject도 있군요.
- 기존 코드 확인 후, 어떻게 일관되게 구현할 지 의견 주시죠.

**Comment by sUpniverse** [comment]
@jhpark816 @hjyun328 

유지 보수 관점 및 code readability 뿐만 아니라 현재 byte array 가 null 혹은 Long이 null인 경우를 비교하여
값을 사용하는 부분에서 혼란을 줄 수 있기 때문에  BKeyObject의 사용이 좋을 것 같습니다.
- long type, byte arrary type 혼합사용 class
  - Element, SMGetElement, SMGetTrimKey
 
현재 BkeyObject 내부에는 
```java

public Long getLongBKey() {
    if (BKeyType.LONG == type) {
      return longBKey;
    } else {
      return null;
    }
 }

public ByteArrayBKey getByteArrayBKey() {
    if (BKeyType.BYTEARRAY == type) {
      return byteArrayBKey;
    } else {
      return null;
    }
  }

  public byte[] getByteArrayBKeyRaw() {
    if (BKeyType.BYTEARRAY == type) {
      return byteArrayBKey.getBytes();
    } else {
      return null;
    }
  }
ublic String getBKeyAsString() {
    if (BKeyType.LONG == type) {
      return String.valueOf(longBKey);
    } else if (BKeyType.BYTEARRAY == type) {
      return BTreeUtil.toHex(byteArrayBKey.getBytes());
    } else {
      return null;
    }
  }
```
위와 같은 메서드 들이 존재합니다.  현재 bkey를 사용하는 곳들은 대부분 생성자를 통해 bkey를 입력받고
long type, byte arrary type, 혹은 String type으로 값을 반환하도록 사용하고 있습니다.

type에 맞게 생성자를 통해 BkeyObject를 생성하고, 원하는 반환값을 이미 구현된 BkeyObject method로 반환해 주면 될 것 같습니다.

아래는 SMGetTrimKey의 변환 예시입니다. 
```java
// 변경 전
public class SMGetTrimKey implements Comparable<SMGetTrimKey> {
  private String key;
  private long bkey;
  private byte[] bytebkey;

  public SMGetTrimKey(String key, Object bkey) {
    this.key = key;
    if (bkey instanceof byte[]) {
      this.bytebkey = new ByteArrayBKey((byte[]) bkey).getBytes();
      this.bkey = -1;
    } else {
      this.bkey = (Long) bkey;
      this.bytebkey = null;
    }
  }
}

// 변경 후
public class SMGetTrimKey implements Comparable<SMGetTrimKey> {
  private String key;
  private BKeyObject bKeyObject;

  public SMGetTrimKey(String key, Object bkey) {
    this.key = key;
    if (bkey instanceof byte[]) {
      this.bKeyObject = new BKeyObject(new ByteArrayBKey(byte[]) bkey));
    } else {
      this.bKeyObject = new BKeyObject((Long) bkey);
    }
  }
}
```

**Comment by jhpark816** [comment]
나도 BKeyObject 사용이 좋다고 봅니다.
@hjyun328 의견 주세요.

**Comment by sUpniverse** [comment]
@jhpark816 @hjyun328 
API 수준에서 long bkey 처리 방식에 대해 조금 더 상세하게 정리합니다.
- bkey 입력시
  - 0, 양수
  - 음수 -> Exception
- bkey 출력시
  - 0, 양수
  - 음수 -> Exception

또한 한가지 더 추가 정보 공유드립니다.
현재 server에서는 maxbkey와 minbkey의 default value를 -1로 지정하여 사용하고 있습니다.
따라서 server로 부터 해당 값(-1)을 수신했을 경우 null처리를 하게 됩니다.

**Comment by hjyun328** [comment]
@jhpark816 @sUpniverse 
다른 타입의 필드를 두개로 두는 것 보다 BKeyObject 클래스를 활용하는 방안이 나아보입니다.

**Comment by sUpniverse** [comment]
pr반영하여 issue close합니다.
