### ISSUE TITLE
from, to를 이용하여 bkey 범위 조회시 BTreeOrder를 사용하지 않는 API 생성

### ISSUE THREAD

**Issue by sUpniverse** [naver/arcus-java-client#435]
현재 asyncBopGetByPosition()에서는 from, to를 이용하여 범위 조회를 수행하고 있다.
이때 BTreeOrder를 함께 인자로 주게 된다. 

이렇게 조회를 수행할 때 잘못된 요청을 줄 수 있다.
```java
asyncBopGetByPosition(KEY, BTreeOrder.ASC, 0, MAX_COUNT);
asyncBopGetByPosition(KEY, BTreeOrder.ASC, MAX_COUNT, 0);
```
이 경우에는 검색조건인 from, to의 범위가 다르지만 똑같이 오름차순으로 조회된다.

```java
asyncBopGetByPosition(KEY, BTreeOrder.DESC, 0, MAX_COUNT);
asyncBopGetByPosition(KEY, BTreeOrder.DESC, MAX_COUNT, 0);
```
반대의 경우 역순(내림차순)으로 조회가 된다.

해당 이유는 내부에서 from, to를 보고 reverse를 판단하여 TreeMap 생성시에 reverse 여부를 넘겨주기 때문이다.
```java
public CollectionFuture<Map<Integer, Element<Object>>> asyncBopGetByPosition(
          String key, BTreeOrder order, int from, int to) {
    BTreeGetByPosition get = new BTreeGetByPosition(order, from, to);
    boolean reverse = from > to;
    return asyncBopGetByPosition(key, get, reverse, collectionTranscoder);
}

TreeMap<Integer, Element<T>> map = new TreeMap<Integer, Element<T>>(
              (reverse) ? Collections.reverseOrder() : null);
```

해당 API를 사용자들이 혼동하여 API를 사용하지 않도록 BtreeOrder를 제거하고
from, to의 범위를 통해 오름차순, 내림차순을 결정하는  API를 추가하도록 하자
```java
asyncBopGetByPosition(String key, int from, int to)
asyncBopGetByPosition(String key, int from, int to, Transcoder<T> tc))
```

**Comment by jhpark816** [comment]
@sUpniverse 

Cache Server ASCII Protocol 확인하니, 아래와 같습니다.
```
bop gbp <key> <order> <position or "position range">\r\n"
```

같은 결과를 다른 2가지로 표현할 수 있다 정도로 이해하고,
수정 없이 그대로 두어야 할 것 같습니다.
어떤가요?

**Comment by hjyun328** [comment]
gbp 명령어를 사용하면 order, from, to에 따라 서버는 아래와 같이 응답합니다.

```
bop gbp key asc 0..1
VALUE 0 2
1 6 111111
2 6 222222
END
bop gbp key desc 0..1
VALUE 0 2
2 6 222222
1 6 111111
END
bop gbp key asc 1..0
VALUE 0 2
2 6 222222
1 6 111111
END
bop gbp key desc 1..0
VALUE 0 2
1 6 111111
2 6 222222
END
```

**Comment by hjyun328** [comment]
클라이언트는 아래와 같이 응답합니다. order는 제대로 적용되지 않는 것으로 보입니다.

```java
for (Integer i : client.asyncBopGetByPosition("key", BTreeOrder.ASC, 0, 1).get().keySet()) {
  System.out.println(i);
}

/*
0
1
*/
```

```java
for (Integer i : client.asyncBopGetByPosition("key", BTreeOrder.DESC, 0, 1).get().keySet()) {
  System.out.println(i);
}
/*
0
1
*/
```

**Comment by sUpniverse** [comment]
기존의 메일 내용을 여기에도 추가해 두도록 하겠습니다.

```java
asyncBopGetByPosition(KEY_PREFIX + id, BTreeOrder.ASC, 0, MAX_COUNT)
```
```
1일차 데이터
bkey data, first position : 1645612605, last position : 1645612605
testValue1
2일차 데이터
bkey data, first position : 1645612605, last position : 1645612606
testValue1
testValue2
3일차 데이터
bkey data, first position : 1645612605, last position : 1645612607
testValue1
testValue2
testValue3
```

​```java
asyncBopGetByPosition(KEY_PREFIX + id, BTreeOrder.ASC, MAX_COUNT, 0)
```
```
1일차 데이터
bkey data, first position : 1645612657, last position : 1645612657
testValue1
2일차 데이터
bkey data, first position : 1645612657, last position : 1645612658
testValue1
testValue2
3일차 데이터
bkey data, first position : 1645612657, last position : 1645612659
testValue1
testValue2
testValue3
```

​```java
asyncBopGetByPosition(KEY_PREFIX + id, BTreeOrder.DESC, 0, MAX_COUNT);
```
1일차 데이터
bkey data, first position : 1645612683, last position : 1645612683
testValue1
2일차 데이터
bkey data, first position : 1645612684, last position : 1645612683
testValue2
testValue1
3일차 데이터
bkey data, first position : 1645612685, last position : 1645612683
testValue3
testValue2
testValue1

```java
asyncBopGetByPosition(KEY_PREFIX + id, BTreeOrder.DESC, MAX_COUNT, 0);
```
1일차 데이터
bkey data, first position : 1645612740, last position : 1645612740
testValue1
2일차 데이터
bkey data, first position : 1645612741, last position : 1645612740
testValue2
testValue1
3일차 데이터
bkey data, first position : 1645612742, last position : 1645612740
testValue3
testValue2
testValue1

**Comment by hjyun328** [comment]
아 클라이언트도 제대로 동작했네요. 테스트를 잘못수행했습니다.

**Comment by hjyun328** [comment]
@sUpniverse @jhpark816 
BTreeOrder가 들어간 API는 제거하지 않고
from, to만 존재하는 API를 추가하는 것도 괜찮을 것 같습니다.

**Comment by hjyun328** [comment]
@jhpark816 
from이 to보다 크다면 ASC일 때 오름차순이 아닌 내림차순으로 결과가 출력되서, order 개념이 모호해지네요. 사용자 입장에서 헷갈리기도하구요. 제 생각엔 order보다는 reverse라는 표현이 적합한 것 같다는 생각이 듭니다. reverse가 true라면 from, to의 결과를 뒤집히기만 하면 되는 것이니까요.

하지만 서버의 동작을 바꾸기는 힘들어보이고, 
클라이언트의 order 인자가 들어간 asyncBopGetByPosition API는 삭제보다는 deprecated 시키고
from, to만 존재하는 API를 추가하는 것이 좋을 것 같다는 생각이 듭니다.

**Comment by jhpark816** [comment]
@sUpniverse 
우선, 테스트 방식에서 무엇이 잘못되어 다른 결과가 나온 것인지 확인해 주면 좋겠습니다.

**Comment by jhpark816** [comment]
@hjyun328 @sUpniverse 

- order 개념이 더욱 명확합니다.
- <order, position> : order 기준으로 해당 position의 element 조회
- <order, position_range> : order 기준으로 해당 position range의 elements 조회
   - 여기 position range에서 from < to 형태로 설정하는 것이 일반적
   - from > to 형태로 설정하더라도 정상 동작이 가능하다고 보면 됩니다.
- 현재 position 값에는 뒤에서부터 몇번째라는 개념이 없습니다.
   - -1, -2, -3. ... (list collection 상의 element index에는 이 개념이 있습니다.)
   - 따라서, 항상 양수의 값만 사용하는 것입니다.
   - 현재 5개 element가 있는 데, MAX_INT_VALUE 위치부터 찾는다는 것이 오히려 어색합니다.
   - 따라서, from < to 형태로 설정하는 것이 일반적입니다.

**Comment by sUpniverse** [comment]
@jhpark816 @hjyun328 

다시 제 테스트 코드를 보니 오류가 있었던거 같습니다. 혼란을 드린거 같습니다.
따라서 형준선임의 테스트대로 결과를 확인하셔야 합니다.

제 테스트에서 오류가 있었던 부분 
```java
long first = resultMap.get(0).getLongBkey();
long last = resultMap.get(resultMap.size() - 1).getLongBkey();
System.out.println("bkey data, smallest bkey : " + first + ", largest bkey : " + last);
```
key를 가져올 당시 iterator를 이용해 bkey를 획득하지 않고, map의 key를 이용해 bkey를 획득하여 가져왔기 때문에 테스트를 진행했을 때 결과가 순서가 지켜지지 않은것 처럼 보였습니다.

```java
client.asyncBopGetByPosition("key", BTreeOrder.ASC, 0, 1)
/*
0={ key: "1", "value" : "111111" }, 1={ key : "2" "value" : "222222" }
*/

client.asyncBopGetByPosition("key", BTreeOrder.ASC, 1, 0)
/*
1={ key : "2" "value" : "222222" }, 0={ key: "1", "value" : "111111" }
*/
--> 이 경우에 iterator를 이용해 조회된 순으로 가져와야 했는데 
제가 map.get(0)으로 postion의 0번째 key 그리고 map.get(map.size() -1)로 postion의 맨 마지막 key를 조회 했기 때문에 순서를 무시하고 postion의 위치로 값을 조회하여서
/*
0={ key: "1", "value" : "111111" }, 1={ key : "2" "value" : "222222" }
*/
해당 결과로 나오게 됐습니다.


그래서 정확히 정리하자면, asyncBopGetByPosition API에서 
(ASC, 0, MAX_COUNT) => 오름차순
(ASC, MAX_COUNT, 0) => 내림차순
(DESC, 0, MAX_COUNT) => 내림차순
(DESC, MAX_COUNT, 0) => 오름차순

의 형태로 작동합니다.

**Comment by sUpniverse** [comment]
그래서 이전에 mail로 역순 조회시에는 DESC를 이용한 조회가 필요하다고 했는데
정정하면, 역순조회를 원할 경우에는 

(ASC, MAX_COUNT, 0) => 내림차순
(DESC, 0, MAX_COUNT) => 내림차순

와 같은 형태의 API 사용이 필요합니다.

**Comment by jhpark816** [comment]
@sUpniverse @hjyun328 
아래와 같이 정리하고, 본 이슈는 close 합니다.

- order 개념은 계속 두는 것으로 하겠습니다.
- get by position 동작을 정확히 이해한 것으로 보겠습니다.
   - 조회 결과는 <position, element> Map이며, 내부적으로 TreeMap 사용합니다.
   - 조회 결과에서 position에 해당하는 element 접근 가능
   - position range 순서로 element 정렬하고 있으므로, 그 순서로 순차 접근 가능

혹, 추가 논의 사항이 있으면, reopen하고 알려주세요.
