### ISSUE TITLE
reconnectQueue의 중복 노드 처리

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#440]
reconnectQueue는 자료구조 형식상(key=시간, value=노드) 중복 노드가 들어갈 수 있다. 

예를 들어, I/O 쓰레드의 한 싸이클에서 i/o failure, continuous timeout / switchover 작업이 연달아 발생된다면 reconnectQueue에 같은 노드가 여러번 저장될 수 있다.

reconnectQueue에 노드가 여러개 존재하는 경우는 사실 문제가 되지 않는다. 
이미 연결된 노드는 아래의 코드에서 재연결하지 않도록 처리되어있기 때문이다. 
https://github.com/naver/arcus-java-client/blob/68e16c774c571ef3ea287a62eae2d1ae1a4765de/src/main/java/net/spy/memcached/MemcachedConnection.java#L921-L924

문제는 zk로부터 node가 remove되는 경우, reconnectQueue에 노드를 딱 하나만 제거한다는 점이다.
https://github.com/naver/arcus-java-client/blob/68e16c774c571ef3ea287a62eae2d1ae1a4765de/src/main/java/net/spy/memcached/MemcachedConnection.java#L272-L278

node가 remove 되기 전에 아래의 순서에 따라 reconnectQueue에 여러 노드가 존재할 수 있어, 사용하지 않는 connection에 관한 leak이 발생할 수 있다.

1. i/o 실패 혹은 기타 이유로 queue delay reconnect
2. switchover로 queue immediate reconnect
3. immediate reconnect 수행 (delay reconnect는 queue에 남아있음)
4. i/o 실패 혹은 기타 이유로 queue delay reconnect
5. ZK로 부터 노드 제거되어 handleNodesToRemove 호출
6. reconnect queue에 중복 노드가 남을 수 있음

또는

1. i/o 실패 혹은 기타 이유로 queue delay reconnect
2. continuous timeout 으로 queue delay reconnect
3. ZK로부터 노드 제거
4. reconnect queue에 중복 노드가 남을 수 있음

또한 reconnectQueue를 제거하는 방식도 모든 노드와 큐를 탐색해야 하므로 매우 비효율적이다. 

connection leak이 나오지 않도록 reconnectQueue 중복 노드 처리 방식을 개선한다.

**Comment by jhpark816** [comment]
@hjyun328 
OK. reconnectQueue에 노드가 중복으로 들어가지 않게 처리합시다.

**Comment by hjyun328** [comment]
@jhpark816 

수정 방향은 2가지가 될 것 같습니다.

reconnect queue에 노드가 중복으로 들어갈 이유는 없다고 판단되어 후자의 방식으로 처리하는게 좋을 것 같습니다.

- 간단하게 handleNodesToRemove 메소드에서 break statement를 제거하고, iterator를 사용하여 remove하는 방법
  - 만약 delay reconnect, immediate reconnect가 동시에 일어난다면, immediate reconnect 이후 갑자기 노드가 reconnect 될 수 있는 문제가 존재함.
  - immediate reconnect는 Master가 Slave 노드로 전환될 때 발생. 따라서 Slave가 갑자기 reconnect가 될 수 있음
- reconnect queue에 중복 노드가 저장되지 않도록 처리하는 방법
