### ISSUE TITLE
Continuous Timeout 기준의 재정리.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#445]
Continuous timeout 발생하면, 현재 연결에 어떤 문제가 있다고 판단하고 reconnect 처리한다.
Continuous timeout 기준에 대해 재검토하고 나은 방안을 설계하여 구현한다. 

- 현재 기준은 "N회 이상의 연속된 timeout 발생" 이다.
   - Async IO 수행하는 환경에서 동시에 요청된 연산들이 많을수록, continuous timeout 발생 확률이 높아진다.
   - 예를 들어,
      - 비슷한 시간에 N개 요청이 동시에 들어오고 (burst 요청)
      - 이를 비동기 IO로 캐시 서버에 보내고 
      - 첫째 요청에 대한 응답이 어떤 이유로 지연되어 timeout 발생한다면,
      - 그 뒤에 있는 요청들도 동시에 timeout 발생할 가능성이 매우 높다. (결국, 연속된 timeout이 된다.)
   - 정리하면,
      - burst 요청이 많은 환경일 수록 continuous timeout 발생 확률이 높아지고,
      - 그렇지 않은 환경이면 continuous timeout 발생이 거의 없다.
- 수정 기준은
   - 요청 환경에 따라서 달라지지 않고, 연결 상태에 어떤 문제가 있는 지의 기준으로 판단하여야 할 것 같다.
   - 이를 위해, "N초 이상 동안 연속된 timeout 발생" 기준이 나은 것 같다.

@SuhwanJang @hjyun328 @sUpniverse 
검토하고, 의견 주세요.

**Comment by jhpark816** [comment]
@hjyun328 
새로운 기준에 대해 의견 주세요.

**Comment by hjyun328** [comment]
@jhpark816 
의견에 동의합니다.
현재의 continuous timeout 처리 구현은 동기 방식에서만 적합한 구현인 것 같습니다.

**Comment by jhpark816** [comment]
@hjyun328 
질문을 잘못 한 것 같군요.
구체적으로 어떤 기준으로 하면 좋은 지에 대해 의견을 물은 것입니다.

우선, 아래 2가지 기준이 모두 만족될 경우메만reconnect 처리해야 할  것 같고요.
각 기준을 어떻게 정하면 좋을까요?
- 연속된 timeout 횟수: 10(??)
- 연속된 timeout 기간(seconds) : 2(??)

**Comment by hjyun328** [comment]
@jhpark816 
read queue에 이미 operation이 많이 찬 상태에서 timeout 기간까지 둔다면 오히려 응용의 응답 성능만 악화될 것 같습니다. 맨 앞에 있는 operation이 제대로 처리되고 있지 않다면 결국 뒤의 operation들도 마찬가지로 처리가 늦어질 것이구요. 이런 상태라면 빠르게 inactive node 상태(delay reconnect)로 전환해서 요청을 DB로 보내는 것이 좋을 것 같습니다.

물론 read queue에 operation이 거의 없는 상황(operation이 timeout 내에 간신히 처리되는 경우)이라면 연속된 timeout 기간이 효과적일 수는 있을 것 같습니다.

따라서 연속된 timeout을 둔다면, 시간은 너무 짧지도 않고 길지도 않아야 할 것 같습니다.

timeout 횟수는 기본 설정 그대로 두고, 
timeout 기간은 1~3초 사이가 적당해보입니다.

**Comment by jhpark816** [comment]
@hjyun328 
아래와 같이 정하시고, 구현 진행하시죠.
- timeout 횟수: 기존 설정 그대로
- timeout 기간: 1.5초 (최대한 짧게)

**Comment by hjyun328** [comment]
https://github.com/naver/arcus-java-client/pull/447 반영되어 클로즈합니다.
