### ISSUE TITLE
CollectionBulkInsertOperationImpl 에서의 pipe operation 설정 검토

### ISSUE THREAD

**Issue by SuhwanJang** [naver/arcus-java-client#448]
Migration 에서 NOT_MY_KEY 처리 구현 시에 pipe 연산은 non-pipe 연산과 처리 방식이 달라서
isPipeOperation() 를 통해 pipe 연산임을 확인해야 합니다. 
Collection Insert 기능의 아래 두 클래스가 있는데 두 클래스 모두 내부적으로 pipe 연산을 사용하지만,
CollectionBulkInsertOperationImpl 는 isPipeOperation()에서 false 를 리턴합니다.
- CollectionBulkInsertOperationImpl : 여러 Key 에 하나의 Element 삽입
- CollectionPipedInsertOperationImpl : 하나의 Key 에 여러 Element 삽입

true 리턴이 맞는 것 같고, 기존에 아마 클래스 레벨 관점에서 정하지 않았나 싶습니다. 
```java
public class CollectionPipedInsertOperationImpl extends OperationImpl
        implements CollectionPipedInsertOperation {
...
  @Override
  public boolean isBulkOperation() {
    return false;
  }

  @Override
  public boolean isPipeOperation() {
    return true;
  }
```

```java
public class CollectionBulkInsertOperationImpl extends OperationImpl
        implements CollectionBulkInsertOperation {
...
  @Override
  public boolean isBulkOperation() {
    return true;
  }

  @Override
  public boolean isPipeOperation() {
    return false;
  }
```

**Comment by hjyun328** [comment]
https://github.com/naver/arcus-java-client/pull/449 반영되어 클로즈합니다.
