### ISSUE TITLE
CI에서 캐싱이 수행이 안되는 현상 검토

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#468]
CI에서 arcus directory와 maven dependency directory를 캐싱하여, CI 작업시 빠르게 arcus를 실행하도록 되어있다.

가끔 캐싱이 안되어 ARCUS를 매번 설치하는 현상이 발생하는데, 그 이유에 대해 원인 분석한다.

https://github.com/naver/arcus-java-client/blob/bd1bd37a48db3d5fb960ab782c796acc3dbda22e/.github/workflows/ci.yml#L24-L36

**Comment by hjyun328** [comment]
아래 CI Job에서는 캐싱이 되었음
https://github.com/naver/arcus-java-client/runs/5691489804?check_suite_focus=true

**Comment by hjyun328** [comment]
최근 Job에서도 캐싱이 성공하였음.
https://github.com/naver/arcus-java-client/runs/5749459767?check_suite_focus=true

**Comment by jhpark816** [comment]
@hjyun328 
기존 캐싱 실패한 이유와
이제 캐싱 성공한 이유를 코멘트 주세요.

**Comment by hjyun328** [comment]
@jhpark816 
7일이 지났거나, 캐시 아이템의 크기가 10GB 이상이라면 evict 시키는 것으로 보입니다.

https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
>GitHub will remove any cache entries that have not been accessed in over 7 days. There is no limit on the number of caches you can store, but the total size of all caches in a repository is limited to 10 GB.
> If you exceed the limit, GitHub will save the new cache but will begin evicting caches until the total size is less than the repository limit.

**Comment by jhpark816** [comment]
@hjyun328 
그러면, 본 이슈는 close 합니다.
