### ISSUE TITLE
Delayed Switchover 개선 

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#471]
switchover 이벤트가 발생하고 old master의 readQ에 non-idempotent operation을 보유할 경우, master의 write 작업을 막고, switchover 작업을 지연한다.

그러나, old master의 readQ의 모든 operation을 읽었다면(REPL_SLAVE 응답을 못받았다면),  switchover 작업이 가능함에도 불구하고 switchover timeout까지 switchover 작업을 보류한다.

현재 switchover timeout이 50ms로 매우 작기 때문에 별 영향은 없지만, timeout에 민감한 응용일 경우, write 작업이 지연되므로, operation timeout이 일어날 가능성이 있다.

REPL_SLAVE 응답, switchover timeout, zk event를 제외한 switchover 작업이 가능한 케이스를 정리하여, delayed switchover를 개선한다.

**Comment by hjyun328** [comment]
switchover가 가능한 케이스를 정리하면 아래와 같다.

1) old master readQ의 모든 operation을 읽었을 때 
2) I/O 도중 old master의 delayed reconnect가 발생할 때

**Comment by jhpark816** [comment]
@hjyun328 
- readQ의 모든 operation에 대해 응답을 받았다면 바로 switchover 한다고 생각했는 데, 아니었군요.
- switchover 가능한 케이스 정리하여 switchover 바로 수행하게 수정되어야 하겠습니다.

**Comment by hjyun328** [comment]
https://github.com/naver/arcus-java-client/pull/472

PR 반영되어 클로즈하겠습니다.
