### ISSUE TITLE
Gracefully Shutdown 개선

### ISSUE THREAD

**Issue by hjyun328** [naver/arcus-java-client#475]
Client의 Shutdown시 Gracefully하게 처리될 수 있도록 개선한다.

1. ArcusClient를 셧다운하게 되면, 어플리케이션이 종료되기 직전에 들어온 요청에 의한 캐시 요청이 거부(IllegalStateException)될 수 있다.

```java
public boolean shutdown(long timeout, TimeUnit unit) {
    shuttingDown = true;
    ...
}

 protected Operation addOp(final String key, final Operation op) {
    ...
    checkState();
    ...
 }

  protected void checkState() {
    if (shuttingDown) {
      throw new IllegalStateException("Shutting down");
    }
    assert isAlive() : "IO Thread is not running.";
  }
```
ArcusClient의 셧다운 작업을 지연시켜, 어플리케이션 종료 직전에 들어온 모든 요청들을 처리할 수 있도록 해야 할 것 같다. 

2. 어플리케이션이 종료될 때, Queue에 남아있는 요청이 모두 처리되어야 할 것 같다. 현재 코드에서 어플리케이션이 종료되면 클라이언트 shutdown에 의해 handleIO 작업은 멈추게되어 Queue에 남아있던 요청들이 처리되지 않아 OperationTimeout이 발생될 것으로 보인다.

```java
// ArcusClient.shutdown(-1, TimeUnit.MILLISECONDS)
public boolean shutdown(long timeout, TimeUnit unit) {
     ...
    shuttingDown = true;
    String baseName = getName();
    setName(baseName + " - SHUTTING DOWN");
    boolean rv = false;
    try {
      // Conditionally wait
      if (timeout > 0) {
        setName(baseName + " - SHUTTING DOWN (waiting)");
        rv = waitForQueues(timeout, unit);  // Queue에 존재하는 모든 요청이 처리될 때까지 대기, 하지만 ArcusClient.shutdown은 해당 코드를 수행하지 않도록 되어있음.
      }
    } finally {
      // But always begin the shutdown sequence
      setName(baseName + " - SHUTTING DOWN (telling client)");
      running = false;
      conn.wakeUpSelector();
      setName(baseName + " - SHUTTING DOWN (informed client)");
      tcService.shutdown();
    }
    return rv;
  }
```

1번 문제를 해결하려면, 어플리케이션에서 try catch로 IllegalStateException을 catch 하거나, 종료시 client의 shutdown API 호출을 2~3초동안 지연시켜 해결할 수 있다. shutdown API 호출을 지연시키면 2번 문제도 함께 해결할 수 있다.

2번 문제는, 클라이언트에서 shutdown시 waitForQueues를 사용하도록 수정한다면, 문제를 해결할 수 있다. 1번 문제도 해결할 수 있지만, waitForQueues 호출 시점 이후에 새로운 캐시 요청이 들어올 수 있으므로, 타이밍상 IllegalStateException이 발생될 수 있다.

**Comment by hjyun328** [comment]
@jhpark816 @sUpniverse 

ArcusClient의 shutdown 메소드에 timeout arg를 추가하여 waitForQueues 메소드를 사용할 수 있도록 해야 할 것 같습니다. 

```java
  @Override
  public void shutdown() {
    super.shutdown();
    // Connect to Arcus server directly, cache manager may be null.
    if (cacheManager != null) {
      cacheManager.shutdown();
    }
    dead = true;
    // if (bulkService != null) {
    //  bulkService.shutdown();
    // }
  }

  /* 아래 메소드를 추가 */
  @Override
  public boolean shutdown(long timeout, TimeUnit unit) {
    super.shutdown(timeout, unit);
    if (cacheManager != null) {
      cacheManager.shutdown();
    }
    dead = true;
  }
```

**Comment by jhpark816** [comment]
@hjyun328 @sUpniverse 
- 위의 1번 문제는 신경쓰지 않아도 될 것 같습니다.
   - 오히려 arcus-java-client shutdown 호출 이후에도 요청이 들어온 사실을 알리는 것이 맞을 것입니다.
   - 따라서, 응용의 graceful shutdown 처리는 응용이 책임져야 할 것입니다.
- 위의 2번 문제는 말한 대로 일정 시간 대기하는 것이 좋겠습니다.
   - 대신, arcus_java_client 외부에서 timeout 시간을 받지 말고 내부에서 정의한 시간을 사용하는 것이 좋겠습니다.
   - 예를 들어, 1~2초 정도의 시간을 주더라도, 내부에 처리할 연산이 없으면 바로 return하는 거죠?

**Comment by hjyun328** [comment]
@jhpark816 
shutdown할 때 내부의 연산을 확인하지 않고, 모든 노드에 VersionOperation을 보내서, 응답을 받을 때까지 기다립니다. 
여기서 latch로 대기하는데, 최대 대기시간은 2초 정도면 충분할 것 같습니다.

```java
  public boolean waitForQueues(long timeout, TimeUnit unit) {
    CountDownLatch blatch = broadcastOp(new BroadcastOpFactory() {
      public Operation newOp(final MemcachedNode n,
                             final CountDownLatch latch) {
        return opFact.noop( 
            new OperationCallback() {
              public void complete() {
                latch.countDown();
              }

              public void receivedStatus(OperationStatus s) {
                // Nothing special when receiving status, only
                // necessary to complete the interface
              }
            });
      }
    }, conn.getLocator().getAll(), false);
    try {
      // XXX:  Perhaps IllegalStateException should be caught here
      // and the check retried.
      return blatch.await(timeout, unit);
    } catch (InterruptedException e) {
      throw new RuntimeException("Interrupted waiting for queues", e);
    }
  }
```

**Comment by jhpark816** [comment]
@hjyun328 
OK.
2초면 충분하다고 봅니다.
Queue에 연산이 있더라도 operation timeout 설정이 1초 미만일 것이므로, 2초 되기 전에 shutdown 처리될 것 같습니다.

대기 방식에 대해 간단히 코멘트하면,
- Queue에 연산이 없으면, version 요청을 보내지 않아도 될 것 같습니다.
- Version 요청을 보내는 것은 앞에 있는 요청이 모두 처리된 것을 보장받기 위한 것이므로,
   모든 노드가 아니라 random 1개 노드에만 version 요청을 보내면 되지 않나요 ?

**Comment by jhpark816** [comment]
@hjyun328 
- 모든 노드로의 queue에 연산이 없다는 것을 확인하는 것이 어려운거죠?
- 모든 노드로 version 요청을 보내는 것이 맞을 것 같습니다.

**Comment by hjyun328** [comment]
@jhpark816 

- 모든 Queue의 Operation 카운트를 얻는 API를 만들어야하고
- 여러 선택된 노드를 대상으로 Bulk 요청을 보내는 로직을 구현해야 합니다.
- 노드마다 서로 다른 operation의 워크 로드를 가질 수 있기 때문에 version op는 한 노드가 아닌 모든 노드에 보내야 할 것 같습니다.

어플리케이션을 종료하는 상황이기 때문에 최적화는 불필요한 것 같습니다.

**Comment by jhpark816** [comment]
@hjyun328 
OK. waitForNode() 구현은 기존 그대로 합시다.

**Comment by hjyun328** [comment]
https://github.com/naver/arcus-java-client/pull/476

PR 반영되어 close 합니다.
