### ISSUE TITLE
compile warning 제거

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#482]
아래의 compile warning을 제거합시다.

```
[WARNING] /home/jhpark/work/arcus-java-client/src/test/manual/net/spy/memcached/btreesmget/SMGetWithCombinationEflagTest.java: Some input files use or override a deprecated API.
[WARNING] /home/jhpark/work/arcus-java-client/src/test/manual/net/spy/memcached/btreesmget/SMGetWithCombinationEflagTest.java: Recompile with -Xlint:deprecation for details.
[WARNING] /home/jhpark/work/arcus-java-client/src/test/java/net/spy/memcached/MemcachedConnectionTest.java: /home/jhpark/work/arcus-java-client/src/test/java/net/spy/memcached/MemcachedConnectionTest.java uses unchecked or unsafe operations.
[WARNING] /home/jhpark/work/arcus-java-client/src/test/java/net/spy/memcached/MemcachedConnectionTest.java: Recompile with -Xlint:unchecked for details.
```

**Comment by uhm0311** [comment]
빌드 시 이 외에도 컴파일 워닝이 많이 뜨는데, 최대한 제거하는 방향으로 작업하겠습니다.

**Comment by uhm0311** [comment]
빌드 시 발생하는 컴파일 워닝 목록입니다.
1. org.junit.internal.runners.JUnit4ClassRunner in org.junit.internal.runners has been deprecated
2. junit.framework.Assert in junit.framework has been deprecated
    - 위의 두 워닝은 JUnit 4를 업그레이드 해야 사라지는 워닝인데, JUnit 5는 Java 8 이상에서만 동작합니다.
    - `@SuppressWarnings()`을 달아서 워닝이 생기지 않게 하거나, 뜨더라도 무시하거나, 자바 버전을 올리면서 JUnit 버전을 업그레이드 하고 테스트 코드를 수정해야 합니다.
    - 두 워닝이 뜨는 곳이 많아 일일이 `@SuppressWarnings()`을 달기보단 다른 방안이 좋을 것 같습니다.
3. Test name 'GetCountBTreeTestWithElementFlagFilter' doesn't match regex `'[A-Z][A-Za-z\d]*Test(s|Case)?|Test[A-Z][A-Za-z\d]*'` 
    - 테스트 클래스의 이름이 Test로 끝나지 않아서 생기는 워닝입니다. 클래스 이름 끝에 Test를 붙이도록 하겠습니다.
4. arcus-java-client/src/test/java/net/spy/memcached/MemcachedConnectionTest.java uses unchecked or unsafe operations
    - reflection으로 가져온 Object 타입의 객체를 타입 체크 없이 형변환 하여 생기는 워닝입니다. 같은 동작을 하는 다른 테스트 코드(TCPMemcachedNodeImplTest 등)에서는 `@SuppressWarnings()`을 붙여서 컴파일 워닝이 뜨지 않도록 구현되어 있습니다. 해당되는 테스트 코드에도 `@SuppressWarnings()`을 붙이는 것이 좋을 것 같습니다.

**Comment by uhm0311** [comment]
4번 컴파일 워닝이 뜨는 부분은 다음의 두 함수입니다. reflection을 통해 객체의 필드를 가져오는 부분입니다.
https://github.com/naver/arcus-java-client/blob/df84407b0442148ce0506ab59f125e1f65344514/src/test/java/net/spy/memcached/MemcachedConnectionTest.java#L143-L156
라인 150과 156에서 컴파일 워닝이 발생합니다.

https://github.com/naver/arcus-java-client/blob/df84407b0442148ce0506ab59f125e1f65344514/src/test/java/net/spy/memcached/MemcachedConnectionTest.java#L216-L229
라인 223과 229에서 컴파일 워닝이 발생합니다.

이와 유사하게 reflection을 통해 객체의 필드를 가져오는 부분이 다른 곳에도 있습니다. `@SuppressWarnings("unchecked")`을 붙여 컴파일 워닝이 뜨지 않도록 한 모습입니다.
https://github.com/naver/arcus-java-client/blob/df84407b0442148ce0506ab59f125e1f65344514/src/test/java/net/spy/memcached/protocol/TCPMemcachedNodeImplTest.java#L38-L49
`@SuppressWarnings("unchecked")`이 없다면 48라인에서 컴파일 워닝이 발생합니다.

TCPMemcachedNodeImplTest에서 `@SuppressWarnings("unchecked")`을 적용한 것 처럼 MemcachedConnectionTest의 두 함수에도 `@SuppressWarnings("unchecked")`을 붙이려고 합니다.

**Comment by jhpark816** [comment]
@uhm0311 
- OK. 이해했습니다.
- `타입 체크 없이 형변환` 상황인 데, 타입 체크할 방법이 있나요 ? 몰라서 질문하는 것입니다.
- 타입 체크 방법이 없다면, 위 코멘트대로 처리하시죠.

@hjyun328 위 내용 검토하기 바랍니다.

**Comment by uhm0311** [comment]
@jhpark816 

> 타입 체크 없이 형변환 상황인 데, 타입 체크할 방법이 있나요 ? 몰라서 질문하는 것입니다.

if (... instanceof ...)으로 감싸야 컴파일 워닝이 뜨지 않는 줄 알았는데, generic이 들어가는 타입으로의 형변환은 항상 컴파일 워닝이 뜨고 generic이 들어가지 않는 타입으로의 형변환은 항상 컴파일 워닝이 뜨지 않는군요.

**Comment by jhpark816** [comment]
@hjyun328 
위 내용 확인하고, 의견 바랍니다.

**Comment by hjyun328** [comment]
@jhpark816 @uhm0311 
spring에서도 제네릭 타입의 형변환의 warning을 unchecked로 사용하고 있네요. 딱히 다른 방법은 없는 것 같습니다.
https://github.com/spring-projects/spring-framework/blob/b595dc1dfad9db534ca7b9e8f46bb9926b88ab5a/spring-webmvc/src/test/java/org/springframework/web/servlet/mvc/method/annotation/MatrixVariablesMapMethodArgumentResolverTests.java#L100-L102

**Comment by jhpark816** [comment]
@hjyun328 @uhm0311 
OK. `@SuppressWarnings("unchecked")`  추가하여 해결합시다.

**Comment by jhpark816** [comment]
위의 PR merge 되었으므로, close 합니다.
