### ISSUE TITLE
[DOC] get bulk 연산의 API 명 수정.

### ISSUE THREAD

**Issue by jhpark816** [naver/arcus-java-client#509]
아래 문서를 보면, API 명이 잘못 기재되어 있습니다.

https://github.com/naver/arcus-java-client/blob/develop/docs/12-arcus-future-get-API.md

잘못된 API명
- asyncBulkGet()
- asyncBulkGets()

**Comment by jhpark816** [comment]
코드도 이상합니다.
`future.get()` 호출의 리턴 값으로 map을 리턴받아야 할 것 같습니다.
그에 따라 결과 부분도 수정이 필요한 것 같습니다.

```java
BulkFuture<Map<String, Object>> future = client.asyncGetBulk(keyList);

Map<String, Object> map = null;
try {
  future.get(6, TimeUnit.MILLISECONDS);
} catch (ExecutionException e) {
  e.printStackTrace();
} catch (TimeoutException e) {
  e.printStackTrace();
}

System.out.println(map);
```

**Comment by sUpniverse** [comment]
@jhpark816 
master branch에서는 해당 return 을 받는것이 생략되어 있는데
현재 develop branch에서는 해당 부분이 수정이 되어 있습니다.

**Comment by jhpark816** [comment]
그러면, API 명만 수정하면 되겠네요.

**Comment by sUpniverse** [comment]
pr 반영하여 이슈 close 합니다.
